In [3]:
import pandas as pd
import ast
import unicodedata

In [19]:
df1 =pd.read_csv('sofifa-career-length.csv')
df2 = pd.read_csv('player-data-full.csv', dtype={'gk_positioning': str})

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21337 entries, 0 to 21336
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             21337 non-null  int64
 1   URL                    21337 non-null  object
 2   Name                   21337 non-null  object
 3   Type                   21337 non-null  object
 4   Season                 21337 non-null  object
 5   Club/Nation            21337 non-null  object
 6   Start_year             21337 non-null  object
 7   End/Recent_year        21337 non-null  object
 8   Career_length          21337 non-null  int64
 9   Start_year_final       21337 non-null  int64
 10  End/Recent_year_final  21337 non-null  int64
dtypes: int64(4), object(7)
memory usage: 1.8+ MB

In [21]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18726 entries, 0 to 18725
Data columns (total 76 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   player_id                  18726 non-null  int64
 1   version                    18726 non-null  object
 2   name                       18726 non-null  object
 3   full_name                  18726 non-null  object
 4   description                18726 non-null  object
 5   image                      18726 non-null  object
 6   height_cm                  18726 non-null  int64
 7   weight_kg                  18726 non-null  int64
 8   dob                        18726 non-null  object
 9   positions                  18726 non-null  object
 10  overall_rating             18726 non-null  int64
 11  potential                  18726 non-null  int64
 12  value                      18726 non-null  object
 13  wage                       18726 non-null  object
 14  preferred_foot             18726 non-null  object
 15  weak_foot                  18726 non-null  int64
 16  skill_moves                18726 non-null  int64
 17  international_reputation   18726 non-null  int64
 18  work_rate                  18726 non-null  object
 19  body_type                  18726 non-null  object
 20  real_face                  18726 non-null  object
 21  release_clause             17134 non-null  object
 22  specialities               1150 non-null   object
 23  club_id                    18632 non-null  float64
 24  club_name                  18632 non-null  object
 25  club_league_id             18632 non-null  float64
 26  club_league_name           18632 non-null  object
 27  club_logo                  18632 non-null  object
 28  club_rating                18632 non-null  float64
 29  club_position              18632 non-null  object
 30  club_kit_number            18632 non-null  float64
 31  club_joined                18721 non-null  object
 32  club_contract_valid_until  18721 non-null  object
 33  country_id                 777 non-null    float64
 34  country_name               777 non-null    object
 35  country_league_id          777 non-null    object
 36  country_league_name        777 non-null    object
 37  country_flag               777 non-null    object
 38  country_rating             777 non-null    float64
 39  country_position           782 non-null    object
 40  country_kit_number         782 non-null    float64
 41  crossing                   18726 non-null  int64
 42  finishing                  18726 non-null  int64
 43  heading_accuracy           18726 non-null  int64
 44  short_passing              18726 non-null  int64
 45  volleys                    18726 non-null  int64
 46  dribbling                  18726 non-null  int64
 47  curve                      18726 non-null  int64
 48  fk_accuracy                18726 non-null  int64
 49  long_passing               18726 non-null  int64
 50  ball_control               18726 non-null  int64
 51  acceleration               18726 non-null  int64
 52  sprint_speed               18726 non-null  int64
 53  agility                    18726 non-null  int64
 54  reactions                  18726 non-null  int64
 55  balance                    18726 non-null  int64
 56  shot_power                 18726 non-null  int64
 57  jumping                    18726 non-null  int64
 58  stamina                    18726 non-null  int64
 59  strength                   18726 non-null  int64
 60  long_shots                 18726 non-null  int64
 61  aggression                 18726 non-null  int64
 62  interceptions              18726 non-null  int64
 63  positioning                18726 non-null  int64
 64  vision                     18726 non-null  int64
 65  penalties                  18726 non-null  int64
 66  composure                  18726 non-null  int64
 67  defensive_awareness        18726 non-null  int64
 68  standing_tackle            18726 non-null  int64
 69  sliding_tackle             18726 non-null  int64
 70  gk_diving                  18726 non-null  int64
 71  gk_handling                18726 non-null  int64
 72  gk_kicking                 18726 non-null  int64
 73  gk_positioning             18694 non-null  object
 74  gk_reflexes                18632 non-null  float64
 75  play_styles                9878 non-null   object
dtypes: float64(8), int64(40), object(28)
memory usage: 10.9+ MB

In [35]:
df2['gk_positioning'] = pd.to_numeric(df2['gk_positioning'], errors='coerce')
df2['gk_positioning'] = df2['gk_positioning'].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [37]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18726 entries, 0 to 18725
Data columns (total 76 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   player_id                  18726 non-null  int64
 1   version                    18726 non-null  object
 2   name                       18726 non-null  object
 3   full_name                  18726 non-null  object
 4   description                18726 non-null  object
 5   image                      18726 non-null  object
 6   height_cm                  18726 non-null  int64
 7   weight_kg                  18726 non-null  int64
 8   dob                        18726 non-null  object
 9   positions                  18726 non-null  object
 10  overall_rating             18726 non-null  int64
 11  potential                  18726 non-null  int64
 12  value                      18726 non-null  object
 13  wage                       18726 non-null  object
 14  preferred_foot             18726 non-null  object
 15  weak_foot                  18726 non-null  int64
 16  skill_moves                18726 non-null  int64
 17  international_reputation   18726 non-null  int64
 18  work_rate                  18726 non-null  object
 19  body_type                  18726 non-null  object
 20  real_face                  18726 non-null  object
 21  release_clause             17134 non-null  object
 22  specialities               1150 non-null   object
 23  club_id                    18632 non-null  float64
 24  club_name                  18632 non-null  object
 25  club_league_id             18632 non-null  float64
 26  club_league_name           18632 non-null  object
 27  club_logo                  18632 non-null  object
 28  club_rating                18632 non-null  float64
 29  club_position              18632 non-null  object
 30  club_kit_number            18632 non-null  float64
 31  club_joined                18721 non-null  object
 32  club_contract_valid_until  18721 non-null  object
 33  country_id                 777 non-null    float64
 34  country_name               777 non-null    object
 35  country_league_id          777 non-null    object
 36  country_league_name        777 non-null    object
 37  country_flag               777 non-null    object
 38  country_rating             777 non-null    float64
 39  country_position           782 non-null    object
 40  country_kit_number         782 non-null    float64
 41  crossing                   18726 non-null  int64
 42  finishing                  18726 non-null  int64
 43  heading_accuracy           18726 non-null  int64
 44  short_passing              18726 non-null  int64
 45  volleys                    18726 non-null  int64
 46  dribbling                  18726 non-null  int64
 47  curve                      18726 non-null  int64
 48  fk_accuracy                18726 non-null  int64
 49  long_passing               18726 non-null  int64
 50  ball_control               18726 non-null  int64
 51  acceleration               18726 non-null  int64
 52  sprint_speed               18726 non-null  int64
 53  agility                    18726 non-null  int64
 54  reactions                  18726 non-null  int64
 55  balance                    18726 non-null  int64
 56  shot_power                 18726 non-null  int64
 57  jumping                    18726 non-null  int64
 58  stamina                    18726 non-null  int64
 59  strength                   18726 non-null  int64
 60  long_shots                 18726 non-null  int64
 61  aggression                 18726 non-null  int64
 62  interceptions              18726 non-null  int64
 63  positioning                18726 non-null  int64
 64  vision                     18726 non-null  int64
 65  penalties                  18726 non-null  int64
 66  composure                  18726 non-null  int64
 67  defensive_awareness        18726 non-null  int64
 68  standing_tackle            18726 non-null  int64
 69  sliding_tackle             18726 non-null  int64
 70  gk_diving                  18726 non-null  int64
 71  gk_handling                18726 non-null  int64
 72  gk_kicking                 18726 non-null  int64
 73  gk_positioning             18632 non-null  float64
 74  gk_reflexes                18632 non-null  float64
 75  play_styles                9878 non-null   object
dtypes: float64(9), int64(40), object(27)
memory usage: 10.9+ MB

In [46]:
df2['gk_positioning'] = df2['gk_positioning'].fillna(0).astype(int)

In [68]:
df2 = df2.drop(['version', 'description', 'overall_rating', 'potential', 'value', 'wage', 'weak_foot', 'skill_moves', 'international_reputation'
               , 'work_rate', 'real_face', 'release_clause', 'club_logo', 'club_rating', 'club_position', 'club_kit_number', 'club_joined'
               , 'club_contract_valid_until', 'country_id', 'country_league_id', 'country_league_name', 'country_flag', 'country_rating', 'country_position', 
                'country_kit_number', 'play_styles', 'image'], axis=1)

In [80]:
df2 = df2.drop(['specialities', 'country_name'], axis=1)

In [82]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18726 entries, 0 to 18725
Data columns (total 47 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            18726 non-null  int64
 1   name                 18726 non-null  object
 2   full_name            18726 non-null  object
 3   height_cm            18726 non-null  int64
 4   weight_kg            18726 non-null  int64
 5   dob                  18726 non-null  object
 6   positions            18726 non-null  object
 7   preferred_foot       18726 non-null  object
 8   body_type            18726 non-null  object
 9   club_id              18632 non-null  float64
 10  club_name            18632 non-null  object
 11  club_league_id       18632 non-null  float64
 12  club_league_name     18632 non-null  object
 13  crossing             18726 non-null  int64
 14  finishing            18726 non-null  int64
 15  heading_accuracy     18726 non-null  int64
 16  short_passing        18726 non-null  int64
 17  volleys              18726 non-null  int64
 18  dribbling            18726 non-null  int64
 19  curve                18726 non-null  int64
 20  fk_accuracy          18726 non-null  int64
 21  long_passing         18726 non-null  int64
 22  ball_control         18726 non-null  int64
 23  acceleration         18726 non-null  int64
 24  sprint_speed         18726 non-null  int64
 25  agility              18726 non-null  int64
 26  reactions            18726 non-null  int64
 27  balance              18726 non-null  int64
 28  shot_power           18726 non-null  int64
 29  jumping              18726 non-null  int64
 30  stamina              18726 non-null  int64
 31  strength             18726 non-null  int64
 32  long_shots           18726 non-null  int64
 33  aggression           18726 non-null  int64
 34  interceptions        18726 non-null  int64
 35  positioning          18726 non-null  int64
 36  vision               18726 non-null  int64
 37  penalties            18726 non-null  int64
 38  composure            18726 non-null  int64
 39  defensive_awareness  18726 non-null  int64
 40  standing_tackle      18726 non-null  int64
 41  sliding_tackle       18726 non-null  int64
 42  gk_diving            18726 non-null  int64
 43  gk_handling          18726 non-null  int64
 44  gk_kicking           18726 non-null  int64
 45  gk_positioning       18726 non-null  int32
 46  gk_reflexes          18632 non-null  float64
dtypes: float64(3), int32(1), int64(35), object(8)
memory usage: 6.6+ MB

In [88]:
df2.isnull().sum()

player_id               0
name                    0
full_name               0
height_cm               0
weight_kg               0
dob                     0
positions               0
preferred_foot          0
body_type               0
club_id                94
club_name              94
club_league_id         94
club_league_name       94
crossing                0
finishing               0
heading_accuracy        0
short_passing           0
volleys                 0
dribbling               0
curve                   0
fk_accuracy             0
long_passing            0
ball_control            0
acceleration            0
sprint_speed            0
agility                 0
reactions               0
balance                 0
shot_power              0
jumping                 0
stamina                 0
strength                0
long_shots              0
aggression              0
interceptions           0
positioning             0
vision                  0
penalties               0
composure               0
defensive_awareness     0
standing_tackle         0
sliding_tackle          0
gk_diving               0
gk_handling             0
gk_kicking              0
gk_positioning          0
gk_reflexes             0
dtype: int64

In [86]:
df2['gk_reflexes'] = df2['gk_reflexes'].fillna(0).astype(int)

In [90]:
df2 = df2.dropna(subset=['club_id', 'club_name', 'club_league_id', 'club_league_name'])

In [92]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18632 entries, 0 to 18725
Data columns (total 47 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   player_id            18632 non-null  int64
 1   name                 18632 non-null  object
 2   full_name            18632 non-null  object
 3   height_cm            18632 non-null  int64
 4   weight_kg            18632 non-null  int64
 5   dob                  18632 non-null  object
 6   positions            18632 non-null  object
 7   preferred_foot       18632 non-null  object
 8   body_type            18632 non-null  object
 9   club_id              18632 non-null  float64
 10  club_name            18632 non-null  object
 11  club_league_id       18632 non-null  float64
 12  club_league_name     18632 non-null  object
 13  crossing             18632 non-null  int64
 14  finishing            18632 non-null  int64
 15  heading_accuracy     18632 non-null  int64
 16  short_passing        18632 non-null  int64
 17  volleys              18632 non-null  int64
 18  dribbling            18632 non-null  int64
 19  curve                18632 non-null  int64
 20  fk_accuracy          18632 non-null  int64
 21  long_passing         18632 non-null  int64
 22  ball_control         18632 non-null  int64
 23  acceleration         18632 non-null  int64
 24  sprint_speed         18632 non-null  int64
 25  agility              18632 non-null  int64
 26  reactions            18632 non-null  int64
 27  balance              18632 non-null  int64
 28  shot_power           18632 non-null  int64
 29  jumping              18632 non-null  int64
 30  stamina              18632 non-null  int64
 31  strength             18632 non-null  int64
 32  long_shots           18632 non-null  int64
 33  aggression           18632 non-null  int64
 34  interceptions        18632 non-null  int64
 35  positioning          18632 non-null  int64
 36  vision               18632 non-null  int64
 37  penalties            18632 non-null  int64
 38  composure            18632 non-null  int64
 39  defensive_awareness  18632 non-null  int64
 40  standing_tackle      18632 non-null  int64
 41  sliding_tackle       18632 non-null  int64
 42  gk_diving            18632 non-null  int64
 43  gk_handling          18632 non-null  int64
 44  gk_kicking           18632 non-null  int64
 45  gk_positioning       18632 non-null  int32
 46  gk_reflexes          18632 non-null  int32
dtypes: float64(2), int32(2), int64(35), object(8)
memory usage: 6.7+ MB

In [108]:
df[df['Name']=='kylian-mbappe'].head()

,Unnamed: 0,URL,Name,Type,Season,Club/Nation,Start_year,End/Recent_year,Career_length,Start_year_final,End/Recent_year_final
6435,6435,https://sofifa.com/player/231747/kylian-mbappe...,kylian-mbappe,League,"['2024/2025', '2023/2024', '2022/2023', '2021/...","['Real Madrid', 'Paris Saint-Germain', 'Paris ...",2015/2016,2024/2025,9,2015,2024
6436,6436,https://sofifa.com/player/231747/kylian-mbappe...,kylian-mbappe,National,"['2024', '2023', '2022', '2021', '2020', '2019...","['France', 'France', 'France', 'France', 'Fran...",2016,2024,8,2016,2024

In [98]:
df2.head()

,player_id,name,full_name,height_cm,weight_kg,dob,positions,preferred_foot,body_type,club_id,...,penalties,composure,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,239085,Erling Haaland,Erling Braut Haaland,195,94,2000-07-21,ST,Left,Unique,10.0,...,86,87,38,47,29,7,14,13,11,7
1,231747,Kylian Mbappé,Kylian Mbappé Lottin,182,75,1998-12-20,"ST,LW",Right,Unique,73.0,...,84,88,26,34,32,13,5,7,11,6
2,192985,Kevin De Bruyne,Kevin De Bruyne,181,75,1991-06-28,"CM,CAM",Right,Unique,10.0,...,83,88,66,70,53,15,13,5,10,13
3,231866,Rodri,Rodrigo Hernández Cascante,191,82,1996-06-22,"CDM,CM",Right,Normal (185+),10.0,...,62,90,92,87,78,10,10,7,14,8
4,202126,Harry Kane,Harry Kane,188,85,1993-07-28,ST,Right,Unique,21.0,...,92,92,46,46,38,8,10,11,14,11

# Converting names to be able to filter and compare them

In [91]:
df.head()

,player_id,name,full_name,height_cm,weight_kg,dob,preferred_foot,body_type,club_id,club_name,...,LM,LW,LWB,RB,RM,RW,RWB,ST,age,league_name
0,19541,Glenn Morris,Glenn James Morris,183,70,1983-12-20,Right,Normal (170-185),1802,Gillingham,...,0,0,0,0,0,0,0,0,41,League Two (ENG 4) [England]
1,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,187,85,1985-02-05,Right,Unique,112139,Al Nassr,...,0,0,0,0,0,0,0,1,40,Pro League (SAU 1) [Saudi Arabia]
2,23823,Andreas Johansson,Karl Tommy Andreas Johansson,184,78,1982-03-10,Right,Lean (170-185),321,Halmstad,...,0,0,0,0,0,0,0,0,43,Allsvenskan (SWE 1) [Sweden]
3,25798,Roque Santa Cruz,Roque Luis Santa Cruz Cantero,191,93,1981-08-16,Right,Normal (185+),111008,Libertad,...,0,0,0,0,0,0,0,1,43,Primera División (PAR 1) [Paraguay]
4,49472,Ludovic Butelle,Ludovic Butelle,188,84,1983-04-03,Left,Normal (185+),379,Stade de Reims,...,0,0,0,0,0,0,0,0,42,Ligue 1 (FRA 1) [France]

In [93]:
name = "Kylian Mbappé Lottin"

normalized_name = unicodedata.normalize('NFD', name).encode('ascii', 'ignore').decode('ascii')
normalized_name = normalized_name.lower().replace(' ', '-')

print(normalized_name)

kylian-mbappe-lottin

In [95]:
def normalize_name(name):
    normalized_name = unicodedata.normalize('NFD', name).encode('ascii', 'ignore').decode('ascii')
    normalized_name = normalized_name.lower().replace(' ', '-')
    return normalized_name

In [97]:
df['normalized_name'] = df['name'].apply(normalize_name)
df['normalized_full_name'] = df['full_name'].apply(normalize_name)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15013 entries, 0 to 15012
Data columns (total 70 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   player_id              15013 non-null  int64
 1   name                   15013 non-null  object
 2   full_name              15013 non-null  object
 3   height_cm              15013 non-null  int64
 4   weight_kg              15013 non-null  int64
 5   dob                    15013 non-null  object
 6   preferred_foot         15013 non-null  object
 7   body_type              15013 non-null  object
 8   club_id                15013 non-null  int64
 9   club_name              15013 non-null  object
 10  club_league_id         15013 non-null  int64
 11  club_league_name       15013 non-null  object
 12  crossing               15013 non-null  int64
 13  finishing              15013 non-null  int64
 14  heading_accuracy       15013 non-null  int64
 15  short_passing          15013 non-null  int64
 16  volleys                15013 non-null  int64
 17  dribbling              15013 non-null  int64
 18  curve                  15013 non-null  int64
 19  fk_accuracy            15013 non-null  int64
 20  long_passing           15013 non-null  int64
 21  ball_control           15013 non-null  int64
 22  acceleration           15013 non-null  int64
 23  sprint_speed           15013 non-null  int64
 24  agility                15013 non-null  int64
 25  reactions              15013 non-null  int64
 26  balance                15013 non-null  int64
 27  shot_power             15013 non-null  int64
 28  jumping                15013 non-null  int64
 29  stamina                15013 non-null  int64
 30  strength               15013 non-null  int64
 31  long_shots             15013 non-null  int64
 32  aggression             15013 non-null  int64
 33  interceptions          15013 non-null  int64
 34  positioning            15013 non-null  int64
 35  vision                 15013 non-null  int64
 36  penalties              15013 non-null  int64
 37  composure              15013 non-null  int64
 38  defensive_awareness    15013 non-null  int64
 39  standing_tackle        15013 non-null  int64
 40  sliding_tackle         15013 non-null  int64
 41  gk_diving              15013 non-null  int64
 42  gk_handling            15013 non-null  int64
 43  gk_kicking             15013 non-null  int64
 44  gk_positioning         15013 non-null  int64
 45  gk_reflexes            15013 non-null  int64
 46  Season                 15013 non-null  object
 47  Club/Nation            15013 non-null  object
 48  Career_length          15013 non-null  int64
 49  Start_year_final       15013 non-null  int64
 50  End/Recent_year_final  15013 non-null  int64
 51  CAM                    15013 non-null  int64
 52  CB                     15013 non-null  int64
 53  CDM                    15013 non-null  int64
 54  CF                     15013 non-null  int64
 55  CM                     15013 non-null  int64
 56  GK                     15013 non-null  int64
 57  LB                     15013 non-null  int64
 58  LM                     15013 non-null  int64
 59  LW                     15013 non-null  int64
 60  LWB                    15013 non-null  int64
 61  RB                     15013 non-null  int64
 62  RM                     15013 non-null  int64
 63  RW                     15013 non-null  int64
 64  RWB                    15013 non-null  int64
 65  ST                     15013 non-null  int64
 66  age                    15013 non-null  int64
 67  league_name            15013 non-null  object
 68  normalized_name        15013 non-null  object
 69  normalized_full_name   15013 non-null  object
dtypes: int64(58), object(12)
memory usage: 8.0+ MB

In [121]:
df2.head()

,player_id,name,full_name,height_cm,weight_kg,dob,positions,preferred_foot,body_type,club_id,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,normalized_name,normalized_full_name
0,239085,Erling Haaland,Erling Braut Haaland,195,94,2000-07-21,ST,Left,Unique,10.0,...,38,47,29,7,14,13,11,7,erling-haaland,erling-braut-haaland
1,231747,Kylian Mbappé,Kylian Mbappé Lottin,182,75,1998-12-20,"ST,LW",Right,Unique,73.0,...,26,34,32,13,5,7,11,6,kylian-mbappe,kylian-mbappe-lottin
2,192985,Kevin De Bruyne,Kevin De Bruyne,181,75,1991-06-28,"CM,CAM",Right,Unique,10.0,...,66,70,53,15,13,5,10,13,kevin-de-bruyne,kevin-de-bruyne
3,231866,Rodri,Rodrigo Hernández Cascante,191,82,1996-06-22,"CDM,CM",Right,Normal (185+),10.0,...,92,87,78,10,10,7,14,8,rodri,rodrigo-hernandez-cascante
4,202126,Harry Kane,Harry Kane,188,85,1993-07-28,ST,Right,Unique,21.0,...,46,46,38,8,10,11,14,11,harry-kane,harry-kane

# Splitting up the dataframe for league and nation transfers

In [124]:
df.head()

,Unnamed: 0,URL,Name,Type,Season,Club/Nation,Start_year,End/Recent_year,Career_length,Start_year_final,End/Recent_year_final
0,0,https://sofifa.com/player/107084/michael-lange...,michael-langer,League,"['2024/2025', '2023/2024', '2022/2023', '2021/...","['FC Schalke 04', 'FC Schalke 04', 'FC Schalke...",2007/2008,2024/2025,17,2007,2024
1,1,https://sofifa.com/player/108061/reto-ziegler/...,reto-ziegler,League,"['2024/2025', '2022/2023', '2022/2023', '2021/...","['FC Sion', 'FC Sion', 'FC Lugano', 'FC Lugano...",2006/2007,2024/2025,18,2006,2024
2,2,https://sofifa.com/player/108061/reto-ziegler/...,reto-ziegler,National,"['2013', '2012', '2011', '2010', '2009']","['Switzerland', 'Switzerland', 'Switzerland', ...",2009,2013,4,2009,2013
3,3,https://sofifa.com/player/118794/andy-lonergan...,andy-lonergan,League,"['2024/2025', '2023/2024', '2022/2023', '2021/...","['Wigan Athletic', 'Everton', 'Everton', 'Ever...",2006/2007,2024/2025,18,2006,2024
4,4,https://sofifa.com/player/125871/hasan-ali-kal...,hasan-ali-kaldirim,League,"['2024/2025', '2023/2024', '2023/2024', '2022/...","['Kayserispor', 'Kayserispor', 'MKE Ankaragücü...",2009/2010,2024/2025,15,2009,2024

In [130]:
league_transfers_df = df.filter(df["Type"] == "League")
national_transfers_df = df.filter(df["Type"] == "National")

In [132]:
league_transfers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21337 entries, 0 to 21336
Empty DataFrame

In [134]:
df['Type'] = df['Type'].str.strip()

league_transfers_df = df[df['Type'] == 'League']

national_transfers_df = df[df['Type'] == 'National']

In [140]:
league_transfers_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18787 entries, 0 to 21336
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             18787 non-null  int64
 1   URL                    18787 non-null  object
 2   Name                   18787 non-null  object
 3   Type                   18787 non-null  object
 4   Season                 18787 non-null  object
 5   Club/Nation            18787 non-null  object
 6   Start_year             18787 non-null  object
 7   End/Recent_year        18787 non-null  object
 8   Career_length          18787 non-null  int64
 9   Start_year_final       18787 non-null  int64
 10  End/Recent_year_final  18787 non-null  int64
dtypes: int64(4), object(7)
memory usage: 1.7+ MB

In [162]:
league_transfers_df.to_csv('league-careers.csv', encoding='utf-8-sig')

In [164]:
national_transfers_df.to_csv('nation-careers.csv', encoding='utf-8-sig')

In [170]:
df2.to_csv('semi_clean_sofifa_players.csv', encoding='utf-8-sig')

In [146]:
national_transfers_df.head()

,Unnamed: 0,URL,Name,Type,Season,Club/Nation,Start_year,End/Recent_year,Career_length,Start_year_final,End/Recent_year_final
2,2,https://sofifa.com/player/108061/reto-ziegler/...,reto-ziegler,National,"['2013', '2012', '2011', '2010', '2009']","['Switzerland', 'Switzerland', 'Switzerland', ...",2009,2013,4,2009,2013
5,5,https://sofifa.com/player/125871/hasan-ali-kal...,hasan-ali-kaldirim,National,"['2020', '2019', '2018', '2017', '2016', '2013...","['Türkiye', 'Türkiye', 'Türkiye', 'Türkiye', '...",2012,2020,8,2012,2020
7,7,https://sofifa.com/player/132740/jesper-hansen...,jesper-hansen,National,"['2020', '2019', '2014', '2013', '2012']","['Denmark', 'Denmark', 'Denmark', 'Denmark', '...",2012,2020,8,2012,2020
9,9,https://sofifa.com/player/135587/niki-maenpaa/...,niki-maenpaa,National,"['2020', '2017', '2016', '2015', '2014', '2013...","['Finland', 'Finland', 'Finland', 'Finland', '...",2008,2020,12,2008,2020
11,11,https://sofifa.com/player/138412/james-milner/...,james-milner,National,"['2015', '2014', '2013', '2012', '2011', '2010...","['England', 'England', 'England', 'England', '...",2009,2015,6,2009,2015

In [166]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18632 entries, 0 to 18725
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   player_id             18632 non-null  int64
 1   name                  18632 non-null  object
 2   full_name             18632 non-null  object
 3   height_cm             18632 non-null  int64
 4   weight_kg             18632 non-null  int64
 5   dob                   18632 non-null  object
 6   positions             18632 non-null  object
 7   preferred_foot        18632 non-null  object
 8   body_type             18632 non-null  object
 9   club_id               18632 non-null  float64
 10  club_name             18632 non-null  object
 11  club_league_id        18632 non-null  float64
 12  club_league_name      18632 non-null  object
 13  crossing              18632 non-null  int64
 14  finishing             18632 non-null  int64
 15  heading_accuracy      18632 non-null  int64
 16  short_passing         18632 non-null  int64
 17  volleys               18632 non-null  int64
 18  dribbling             18632 non-null  int64
 19  curve                 18632 non-null  int64
 20  fk_accuracy           18632 non-null  int64
 21  long_passing          18632 non-null  int64
 22  ball_control          18632 non-null  int64
 23  acceleration          18632 non-null  int64
 24  sprint_speed          18632 non-null  int64
 25  agility               18632 non-null  int64
 26  reactions             18632 non-null  int64
 27  balance               18632 non-null  int64
 28  shot_power            18632 non-null  int64
 29  jumping               18632 non-null  int64
 30  stamina               18632 non-null  int64
 31  strength              18632 non-null  int64
 32  long_shots            18632 non-null  int64
 33  aggression            18632 non-null  int64
 34  interceptions         18632 non-null  int64
 35  positioning           18632 non-null  int64
 36  vision                18632 non-null  int64
 37  penalties             18632 non-null  int64
 38  composure             18632 non-null  int64
 39  defensive_awareness   18632 non-null  int64
 40  standing_tackle       18632 non-null  int64
 41  sliding_tackle        18632 non-null  int64
 42  gk_diving             18632 non-null  int64
 43  gk_handling           18632 non-null  int64
 44  gk_kicking            18632 non-null  int64
 45  gk_positioning        18632 non-null  int32
 46  gk_reflexes           18632 non-null  int32
 47  normalized_name       18632 non-null  object
 48  normalized_full_name  18632 non-null  object
dtypes: float64(2), int32(2), int64(35), object(10)
memory usage: 7.0+ MB

In [148]:
merged_league_name = df2.merge(league_transfers_df, left_on='normalized_name', right_on='Name', how='left', suffixes=('', '_league'))
merged_national_name = df2.merge(national_transfers_df, left_on='normalized_name', right_on='Name', how='left', suffixes=('', '_national'))


merged_league_full = df2.merge(league_transfers_df, left_on='normalized_full_name', right_on='Name', how='left', suffixes=('', '_league'))
merged_national_full = df2.merge(national_transfers_df, left_on='normalized_full_name', right_on='Name', how='left', suffixes=('', '_national'))

final_merged = merged_league_name.combine_first(merged_league_full)
final_merged = final_merged.combine_first(merged_national_name)
final_merged = final_merged.combine_first(merged_national_full)

print(final_merged.head())

   player_id             name                   full_name  height_cm  \
0     239085   Erling Haaland        Erling Braut Haaland        195
1     231747    Kylian Mbappé        Kylian Mbappé Lottin        182
2     192985  Kevin De Bruyne             Kevin De Bruyne        181
3     231866            Rodri  Rodrigo Hernández Cascante        191
4     202126       Harry Kane                  Harry Kane        188

   weight_kg         dob positions preferred_foot      body_type  club_id  \
0         94  2000-07-21        ST           Left         Unique     10.0
1         75  1998-12-20     ST,LW          Right         Unique     73.0
2         75  1991-06-28    CM,CAM          Right         Unique     10.0
3         82  1996-06-22    CDM,CM          Right  Normal (185+)     10.0
4         85  1993-07-28        ST          Right         Unique     21.0

   ...                                                URL  \
0  ...  https://sofifa.com/player/239085/erling-haalan...
1  ...  https://sofifa.com/player/231747/kylian-mbappe...
2  ...  https://sofifa.com/player/192985/kevin-de-bruy...
3  ...  https://sofifa.com/player/231866/rodrigo-herna...
4  ...  https://sofifa.com/player/202126/harry-kane/25...

                         Name    Type  \
0              erling-haaland  League
1               kylian-mbappe  League
2             kevin-de-bruyne  League
3  rodrigo-hernandez-cascante  League
4                  harry-kane  League

                                              Season  \
0  ['2024/2025', '2023/2024', '2022/2023', '2021/...
1  ['2024/2025', '2023/2024', '2022/2023', '2021/...
2  ['2024/2025', '2023/2024', '2022/2023', '2021/...
3  ['2024/2025', '2023/2024', '2022/2023', '2021/...
4  ['2024/2025', '2023/2024', '2023/2024', '2022/...

                                         Club/Nation  Start_year  \
0  ['Manchester City', 'Manchester City', 'Manche...   2016/2017
1  ['Real Madrid', 'Paris Saint-Germain', 'Paris ...   2015/2016
2  ['Manchester City', 'Manchester City', 'Manche...   2009/2010
3  ['Manchester City', 'Manchester City', 'Manche...   2015/2016
4  ['FC Bayern München', 'FC Bayern München', 'To...   2010/2011

   End/Recent_year  Career_length  Start_year_final  End/Recent_year_final
0        2024/2025            8.0            2016.0                 2024.0
1        2024/2025            9.0            2015.0                 2024.0
2        2024/2025           15.0            2009.0                 2024.0
3        2024/2025            9.0            2015.0                 2024.0
4        2024/2025           14.0            2010.0                 2024.0

[5 rows x 60 columns]

In [150]:
final_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18789 entries, 0 to 18788
Data columns (total 60 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   player_id              18789 non-null  int64
 1   name                   18789 non-null  object
 2   full_name              18789 non-null  object
 3   height_cm              18789 non-null  int64
 4   weight_kg              18789 non-null  int64
 5   dob                    18789 non-null  object
 6   positions              18789 non-null  object
 7   preferred_foot         18789 non-null  object
 8   body_type              18789 non-null  object
 9   club_id                18789 non-null  float64
 10  club_name              18789 non-null  object
 11  club_league_id         18789 non-null  float64
 12  club_league_name       18789 non-null  object
 13  crossing               18789 non-null  int64
 14  finishing              18789 non-null  int64
 15  heading_accuracy       18789 non-null  int64
 16  short_passing          18789 non-null  int64
 17  volleys                18789 non-null  int64
 18  dribbling              18789 non-null  int64
 19  curve                  18789 non-null  int64
 20  fk_accuracy            18789 non-null  int64
 21  long_passing           18789 non-null  int64
 22  ball_control           18789 non-null  int64
 23  acceleration           18789 non-null  int64
 24  sprint_speed           18789 non-null  int64
 25  agility                18789 non-null  int64
 26  reactions              18789 non-null  int64
 27  balance                18789 non-null  int64
 28  shot_power             18789 non-null  int64
 29  jumping                18789 non-null  int64
 30  stamina                18789 non-null  int64
 31  strength               18789 non-null  int64
 32  long_shots             18789 non-null  int64
 33  aggression             18789 non-null  int64
 34  interceptions          18789 non-null  int64
 35  positioning            18789 non-null  int64
 36  vision                 18789 non-null  int64
 37  penalties              18789 non-null  int64
 38  composure              18789 non-null  int64
 39  defensive_awareness    18789 non-null  int64
 40  standing_tackle        18789 non-null  int64
 41  sliding_tackle         18789 non-null  int64
 42  gk_diving              18789 non-null  int64
 43  gk_handling            18789 non-null  int64
 44  gk_kicking             18789 non-null  int64
 45  gk_positioning         18789 non-null  int32
 46  gk_reflexes            18789 non-null  int32
 47  normalized_name        18789 non-null  object
 48  normalized_full_name   18789 non-null  object
 49  Unnamed: 0             15591 non-null  float64
 50  URL                    15591 non-null  object
 51  Name                   15591 non-null  object
 52  Type                   15591 non-null  object
 53  Season                 15591 non-null  object
 54  Club/Nation            15591 non-null  object
 55  Start_year             15591 non-null  object
 56  End/Recent_year        15591 non-null  object
 57  Career_length          15591 non-null  float64
 58  Start_year_final       15591 non-null  float64
 59  End/Recent_year_final  15591 non-null  float64
dtypes: float64(6), int32(2), int64(35), object(17)
memory usage: 8.6+ MB

In [152]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18632 entries, 0 to 18725
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   player_id             18632 non-null  int64
 1   name                  18632 non-null  object
 2   full_name             18632 non-null  object
 3   height_cm             18632 non-null  int64
 4   weight_kg             18632 non-null  int64
 5   dob                   18632 non-null  object
 6   positions             18632 non-null  object
 7   preferred_foot        18632 non-null  object
 8   body_type             18632 non-null  object
 9   club_id               18632 non-null  float64
 10  club_name             18632 non-null  object
 11  club_league_id        18632 non-null  float64
 12  club_league_name      18632 non-null  object
 13  crossing              18632 non-null  int64
 14  finishing             18632 non-null  int64
 15  heading_accuracy      18632 non-null  int64
 16  short_passing         18632 non-null  int64
 17  volleys               18632 non-null  int64
 18  dribbling             18632 non-null  int64
 19  curve                 18632 non-null  int64
 20  fk_accuracy           18632 non-null  int64
 21  long_passing          18632 non-null  int64
 22  ball_control          18632 non-null  int64
 23  acceleration          18632 non-null  int64
 24  sprint_speed          18632 non-null  int64
 25  agility               18632 non-null  int64
 26  reactions             18632 non-null  int64
 27  balance               18632 non-null  int64
 28  shot_power            18632 non-null  int64
 29  jumping               18632 non-null  int64
 30  stamina               18632 non-null  int64
 31  strength              18632 non-null  int64
 32  long_shots            18632 non-null  int64
 33  aggression            18632 non-null  int64
 34  interceptions         18632 non-null  int64
 35  positioning           18632 non-null  int64
 36  vision                18632 non-null  int64
 37  penalties             18632 non-null  int64
 38  composure             18632 non-null  int64
 39  defensive_awareness   18632 non-null  int64
 40  standing_tackle       18632 non-null  int64
 41  sliding_tackle        18632 non-null  int64
 42  gk_diving             18632 non-null  int64
 43  gk_handling           18632 non-null  int64
 44  gk_kicking            18632 non-null  int64
 45  gk_positioning        18632 non-null  int32
 46  gk_reflexes           18632 non-null  int32
 47  normalized_name       18632 non-null  object
 48  normalized_full_name  18632 non-null  object
dtypes: float64(2), int32(2), int64(35), object(10)
memory usage: 7.0+ MB

In [156]:
final_merged['player_id'].unique()

array([239085, 231747, 192985, ...,  71064, 269541, 277493], dtype=int64)

In [160]:
duplicates = df2[df2['player_id'].duplicated()]
print(duplicates)

      player_id                  name                         full_name  \
1444     262929        Vinicius Souza           Vinicius de Souza Costa
1466     268573  Federico Baschirotto              Federico Baschirotto
1478     277537                 Natan           Natan Bernardo de Souza
1507     266797        Gastón Álvarez         Pedro Gastón Álvarez Sosa
1515     264755    Daniel Felipe Ruiz         Daniel Felipe Ruiz Rivera
1520     265526      Guillaume Restes                  Guillaume Restes
1525     275771           Igor Thiago  Igor Thiago Nascimento Rodrigues
1553     268621      Gastón Hernández             Gastón Alan Hernández
1600     269421            Jota Silva         João Pedro Ferreira Silva
1604     274288          Oscar Gloukh                      Oscar Gloukh
1615     269176           Alejo Veliz                       Alejo Véliz
1631     263296        Luciano Gondou     Luciano Emilio Gondou Zanelli
1638     268421            Mathys Tel                        Mathys Tel
1647     268683    Michael Folorunsho        Michael Ijemuan Folorunsho
1661     263829               Vitinha    Vítor Manuel Carvalho Oliveira
1673     279709         Lucas Beraldo               Lucas Lopes Beraldo
1675     267680          Abdul Fatawu             Abdul Fatawu Issahaku
1699     265650             Saúl Coco   Saúl Basilio Coco-Bassey Oubiña
1732     263880          Agirrezabala                Julen Agirrezabala
1749     271574            Rico Lewis                        Rico Lewis
1761     270559          Tiago Santos             Tiago Santos Carvalho
1769     263396                Copete          José Manuel Arias Copete
1809     263673                Andrew           Andrew da Silva Ventura
1817     278013          Saba Sazonov                      Saba Sazonov

      height_cm  weight_kg         dob  positions preferred_foot  \
1444        187         80  1999-06-17     CDM,CM          Right
1466        184         77  1996-09-20         CB          Right
1478        188         85  2001-02-06         CB           Left
1507        184         72  2000-03-24  CB,LB,LWB           Left
1515        171         70  2001-07-30         LM           Left
1520        188         82  2005-03-11         GK           Left
1525        191         88  2001-06-26         ST          Right
1553        185         76  1998-01-19         CB          Right
1600        179         73  1999-08-01   RW,ST,LW          Right
1604        170         68  2004-04-01        CAM          Right
1615        186         77  2003-09-19         ST          Right
1631        189         83  2001-06-22      ST,RW           Left
1638        183         77  2005-04-27   ST,LM,RM          Right
1647        185         78  1998-02-07  CM,CAM,ST          Right
1661        178         74  2000-03-15         ST          Right
1673        182         78  2003-11-24      CB,LB           Left
1675        177         73  2004-03-08         RW           Left
1699        188         76  1999-02-09         CB          Right
1732        187         80  2000-12-26         GK           Left
1749        169         70  2004-11-21     RB,CDM          Right
1761        175         67  2002-07-23         RB          Right
1769        192         73  1999-10-10         CB           Left
1809        189         76  2001-07-01         GK          Right
1817        194         84  2002-02-01         CB          Right

             body_type   club_id  ... defensive_awareness  standing_tackle  \
1444     Normal (185+)    1794.0  ...                  74               77
1466  Stocky (170-185)     347.0  ...                  80               73
1478     Normal (185+)      48.0  ...                  80               78
1507    Lean (170-185)    1860.0  ...                  79               72
1515  Normal (170-185)  101105.0  ...                  44               52
1520     Normal (185+)    1809.0  ...                  11               16
1525     Stocky (185+)     231.0  ...                  36               38
1553     Normal (185+)    1013.0  ...                  77               77
1600  Normal (170-185)    1887.0  ...                  37               36
1604     Normal (170-)     191.0  ...                  42               32
1615     Normal (185+)     481.0  ...                  17               23
1631       Lean (185+)  111019.0  ...                  35               35
1638  Normal (170-185)      21.0  ...                  22               27
1647     Stocky (185+)     206.0  ...                  67               72
1661  Normal (170-185)  110556.0  ...                  23               29
1673  Normal (170-185)      73.0  ...                  72               78
1675  Normal (170-185)      95.0  ...                  36               48
1699     Normal (185+)     472.0  ...                  79               76
1732       Lean (185+)     448.0  ...                  10               13
1749       Lean (170-)      10.0  ...                  71               74
1761  Normal (170-185)      65.0  ...                  72               75
1769       Lean (185+)     453.0  ...                  77               78
1809       Lean (185+)    1888.0  ...                  10                8
1817     Normal (185+)      54.0  ...                  74               75

     sliding_tackle  gk_diving  gk_handling  gk_kicking  gk_positioning  \
1444             75         14           14           9              13
1466             71         14           11          10               6
1478             74         14           13           8               8
1507             73         10           11          12               8
1515             48          9           11          14              11
1520             14         76           72          75              73
1525             23         14            6          14              15
1553             75         10            9          13              14
1600             33         14            6           9               5
1604             28          6            8          13              13
1615             21          7            6           7               6
1631             27          6           10           6              14
1638             32         12            9          15               7
1647             67         14           12          10              12
1661             22          5            8           6               9
1673             77         11           14          15              12
1675             45         13            7           7               7
1699             73          5            8           7              13
1732             12         76           74          73              77
1749             72         11            8          11              12
1761             74         10            7          15               7
1769             76         11           13           9              13
1809             17         76           73          74              72
1817             72         11            8           7              12

      gk_reflexes       normalized_name              normalized_full_name
1444            8        vinicius-souza           vinicius-de-souza-costa
1466           12  federico-baschirotto              federico-baschirotto
1478            6                 natan           natan-bernardo-de-souza
1507           12        gaston-alvarez         pedro-gaston-alvarez-sosa
1515           12    daniel-felipe-ruiz         daniel-felipe-ruiz-rivera
1520           78      guillaume-restes                  guillaume-restes
1525           11           igor-thiago  igor-thiago-nascimento-rodrigues
1553           10      gaston-hernandez             gaston-alan-hernandez
1600           15            jota-silva         joao-pedro-ferreira-silva
1604            5          oscar-gloukh                      oscar-gloukh
1615           11           alejo-veliz                       alejo-veliz
1631           13        luciano-gondou     luciano-emilio-gondou-zanelli
1638           11            mathys-tel                        mathys-tel
1647            8    michael-folorunsho        michael-ijemuan-folorunsho
1661           15               vitinha    vitor-manuel-carvalho-oliveira
1673            8         lucas-beraldo               lucas-lopes-beraldo
1675            5          abdul-fatawu             abdul-fatawu-issahaku
1699            9             saul-coco   saul-basilio-coco-bassey-oubina
1732           73          agirrezabala                julen-agirrezabala
1749           13            rico-lewis                        rico-lewis
1761           13          tiago-santos             tiago-santos-carvalho
1769            8                copete          jose-manuel-arias-copete
1809           77                andrew           andrew-da-silva-ventura
1817            7          saba-sazonov                      saba-sazonov

[24 rows x 49 columns]

In [265]:
df_players =pd.read_csv('semi_clean_sofifa_players.csv')
df_league =pd.read_csv('league-careers.csv')
df_nation =pd.read_csv('nation-careers.csv')

In [267]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18632 entries, 0 to 18631
Data columns (total 50 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            18632 non-null  int64
 1   player_id             18632 non-null  int64
 2   name                  18632 non-null  object
 3   full_name             18632 non-null  object
 4   height_cm             18632 non-null  int64
 5   weight_kg             18632 non-null  int64
 6   dob                   18632 non-null  object
 7   positions             18632 non-null  object
 8   preferred_foot        18632 non-null  object
 9   body_type             18632 non-null  object
 10  club_id               18632 non-null  float64
 11  club_name             18632 non-null  object
 12  club_league_id        18632 non-null  float64
 13  club_league_name      18632 non-null  object
 14  crossing              18632 non-null  int64
 15  finishing             18632 non-null  int64
 16  heading_accuracy      18632 non-null  int64
 17  short_passing         18632 non-null  int64
 18  volleys               18632 non-null  int64
 19  dribbling             18632 non-null  int64
 20  curve                 18632 non-null  int64
 21  fk_accuracy           18632 non-null  int64
 22  long_passing          18632 non-null  int64
 23  ball_control          18632 non-null  int64
 24  acceleration          18632 non-null  int64
 25  sprint_speed          18632 non-null  int64
 26  agility               18632 non-null  int64
 27  reactions             18632 non-null  int64
 28  balance               18632 non-null  int64
 29  shot_power            18632 non-null  int64
 30  jumping               18632 non-null  int64
 31  stamina               18632 non-null  int64
 32  strength              18632 non-null  int64
 33  long_shots            18632 non-null  int64
 34  aggression            18632 non-null  int64
 35  interceptions         18632 non-null  int64
 36  positioning           18632 non-null  int64
 37  vision                18632 non-null  int64
 38  penalties             18632 non-null  int64
 39  composure             18632 non-null  int64
 40  defensive_awareness   18632 non-null  int64
 41  standing_tackle       18632 non-null  int64
 42  sliding_tackle        18632 non-null  int64
 43  gk_diving             18632 non-null  int64
 44  gk_handling           18632 non-null  int64
 45  gk_kicking            18632 non-null  int64
 46  gk_positioning        18632 non-null  int64
 47  gk_reflexes           18632 non-null  int64
 48  normalized_name       18632 non-null  object
 49  normalized_full_name  18632 non-null  object
dtypes: float64(2), int64(38), object(10)
memory usage: 7.1+ MB

In [269]:
df_league.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18787 entries, 0 to 18786
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           18787 non-null  int64
 1   Unnamed: 0             18787 non-null  int64
 2   URL                    18787 non-null  object
 3   Name                   18787 non-null  object
 4   Type                   18787 non-null  object
 5   Season                 18787 non-null  object
 6   Club/Nation            18787 non-null  object
 7   Start_year             18787 non-null  object
 8   End/Recent_year        18787 non-null  object
 9   Career_length          18787 non-null  int64
 10  Start_year_final       18787 non-null  int64
 11  End/Recent_year_final  18787 non-null  int64
dtypes: int64(5), object(7)
memory usage: 1.7+ MB

In [271]:
df_nation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2550 entries, 0 to 2549
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           2550 non-null   int64
 1   Unnamed: 0             2550 non-null   int64
 2   URL                    2550 non-null   object
 3   Name                   2550 non-null   object
 4   Type                   2550 non-null   object
 5   Season                 2550 non-null   object
 6   Club/Nation            2550 non-null   object
 7   Start_year             2550 non-null   object
 8   End/Recent_year        2550 non-null   object
 9   Career_length          2550 non-null   int64
 10  Start_year_final       2550 non-null   int64
 11  End/Recent_year_final  2550 non-null   int64
dtypes: int64(5), object(7)
memory usage: 239.2+ KB

In [273]:
df_players.head()

,Unnamed: 0,player_id,name,full_name,height_cm,weight_kg,dob,positions,preferred_foot,body_type,...,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,normalized_name,normalized_full_name
0,0,239085,Erling Haaland,Erling Braut Haaland,195,94,2000-07-21,ST,Left,Unique,...,38,47,29,7,14,13,11,7,erling-haaland,erling-braut-haaland
1,1,231747,Kylian Mbappé,Kylian Mbappé Lottin,182,75,1998-12-20,"ST,LW",Right,Unique,...,26,34,32,13,5,7,11,6,kylian-mbappe,kylian-mbappe-lottin
2,2,192985,Kevin De Bruyne,Kevin De Bruyne,181,75,1991-06-28,"CM,CAM",Right,Unique,...,66,70,53,15,13,5,10,13,kevin-de-bruyne,kevin-de-bruyne
3,3,231866,Rodri,Rodrigo Hernández Cascante,191,82,1996-06-22,"CDM,CM",Right,Normal (185+),...,92,87,78,10,10,7,14,8,rodri,rodrigo-hernandez-cascante
4,4,202126,Harry Kane,Harry Kane,188,85,1993-07-28,ST,Right,Unique,...,46,46,38,8,10,11,14,11,harry-kane,harry-kane

In [192]:
# merge1 = df_players.merge(df_league, left_on='normalized_name', right_on='Name', how='left', suffixes=('_players', '_league'))

In [275]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18632 entries, 0 to 18725
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   player_id             18632 non-null  int64
 1   name                  18632 non-null  object
 2   full_name             18632 non-null  object
 3   height_cm             18632 non-null  int64
 4   weight_kg             18632 non-null  int64
 5   dob                   18632 non-null  object
 6   positions             18632 non-null  object
 7   preferred_foot        18632 non-null  object
 8   body_type             18632 non-null  object
 9   club_id               18632 non-null  float64
 10  club_name             18632 non-null  object
 11  club_league_id        18632 non-null  float64
 12  club_league_name      18632 non-null  object
 13  crossing              18632 non-null  int64
 14  finishing             18632 non-null  int64
 15  heading_accuracy      18632 non-null  int64
 16  short_passing         18632 non-null  int64
 17  volleys               18632 non-null  int64
 18  dribbling             18632 non-null  int64
 19  curve                 18632 non-null  int64
 20  fk_accuracy           18632 non-null  int64
 21  long_passing          18632 non-null  int64
 22  ball_control          18632 non-null  int64
 23  acceleration          18632 non-null  int64
 24  sprint_speed          18632 non-null  int64
 25  agility               18632 non-null  int64
 26  reactions             18632 non-null  int64
 27  balance               18632 non-null  int64
 28  shot_power            18632 non-null  int64
 29  jumping               18632 non-null  int64
 30  stamina               18632 non-null  int64
 31  strength              18632 non-null  int64
 32  long_shots            18632 non-null  int64
 33  aggression            18632 non-null  int64
 34  interceptions         18632 non-null  int64
 35  positioning           18632 non-null  int64
 36  vision                18632 non-null  int64
 37  penalties             18632 non-null  int64
 38  composure             18632 non-null  int64
 39  defensive_awareness   18632 non-null  int64
 40  standing_tackle       18632 non-null  int64
 41  sliding_tackle        18632 non-null  int64
 42  gk_diving             18632 non-null  int64
 43  gk_handling           18632 non-null  int64
 44  gk_kicking            18632 non-null  int64
 45  gk_positioning        18632 non-null  int32
 46  gk_reflexes           18632 non-null  int32
 47  normalized_name       18632 non-null  object
 48  normalized_full_name  18632 non-null  object
dtypes: float64(2), int32(2), int64(35), object(10)
memory usage: 7.0+ MB

In [277]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18632 entries, 0 to 18631
Data columns (total 50 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            18632 non-null  int64
 1   player_id             18632 non-null  int64
 2   name                  18632 non-null  object
 3   full_name             18632 non-null  object
 4   height_cm             18632 non-null  int64
 5   weight_kg             18632 non-null  int64
 6   dob                   18632 non-null  object
 7   positions             18632 non-null  object
 8   preferred_foot        18632 non-null  object
 9   body_type             18632 non-null  object
 10  club_id               18632 non-null  float64
 11  club_name             18632 non-null  object
 12  club_league_id        18632 non-null  float64
 13  club_league_name      18632 non-null  object
 14  crossing              18632 non-null  int64
 15  finishing             18632 non-null  int64
 16  heading_accuracy      18632 non-null  int64
 17  short_passing         18632 non-null  int64
 18  volleys               18632 non-null  int64
 19  dribbling             18632 non-null  int64
 20  curve                 18632 non-null  int64
 21  fk_accuracy           18632 non-null  int64
 22  long_passing          18632 non-null  int64
 23  ball_control          18632 non-null  int64
 24  acceleration          18632 non-null  int64
 25  sprint_speed          18632 non-null  int64
 26  agility               18632 non-null  int64
 27  reactions             18632 non-null  int64
 28  balance               18632 non-null  int64
 29  shot_power            18632 non-null  int64
 30  jumping               18632 non-null  int64
 31  stamina               18632 non-null  int64
 32  strength              18632 non-null  int64
 33  long_shots            18632 non-null  int64
 34  aggression            18632 non-null  int64
 35  interceptions         18632 non-null  int64
 36  positioning           18632 non-null  int64
 37  vision                18632 non-null  int64
 38  penalties             18632 non-null  int64
 39  composure             18632 non-null  int64
 40  defensive_awareness   18632 non-null  int64
 41  standing_tackle       18632 non-null  int64
 42  sliding_tackle        18632 non-null  int64
 43  gk_diving             18632 non-null  int64
 44  gk_handling           18632 non-null  int64
 45  gk_kicking            18632 non-null  int64
 46  gk_positioning        18632 non-null  int64
 47  gk_reflexes           18632 non-null  int64
 48  normalized_name       18632 non-null  object
 49  normalized_full_name  18632 non-null  object
dtypes: float64(2), int64(38), object(10)
memory usage: 7.1+ MB

# Calculate age

In [280]:
df_players['dob'].head()

0    2000-07-21
1    1998-12-20
2    1991-06-28
3    1996-06-22
4    1993-07-28
Name: dob, dtype: object

In [282]:
df_players['dob'] = pd.to_datetime(df_players['dob'], errors='coerce')

df_players['age'] = (pd.to_datetime('today') - df_players['dob']).dt.days // 365

In [284]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18632 entries, 0 to 18631
Data columns (total 51 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            18632 non-null  int64
 1   player_id             18632 non-null  int64
 2   name                  18632 non-null  object
 3   full_name             18632 non-null  object
 4   height_cm             18632 non-null  int64
 5   weight_kg             18632 non-null  int64
 6   dob                   18632 non-null  datetime64[ns]
 7   positions             18632 non-null  object
 8   preferred_foot        18632 non-null  object
 9   body_type             18632 non-null  object
 10  club_id               18632 non-null  float64
 11  club_name             18632 non-null  object
 12  club_league_id        18632 non-null  float64
 13  club_league_name      18632 non-null  object
 14  crossing              18632 non-null  int64
 15  finishing             18632 non-null  int64
 16  heading_accuracy      18632 non-null  int64
 17  short_passing         18632 non-null  int64
 18  volleys               18632 non-null  int64
 19  dribbling             18632 non-null  int64
 20  curve                 18632 non-null  int64
 21  fk_accuracy           18632 non-null  int64
 22  long_passing          18632 non-null  int64
 23  ball_control          18632 non-null  int64
 24  acceleration          18632 non-null  int64
 25  sprint_speed          18632 non-null  int64
 26  agility               18632 non-null  int64
 27  reactions             18632 non-null  int64
 28  balance               18632 non-null  int64
 29  shot_power            18632 non-null  int64
 30  jumping               18632 non-null  int64
 31  stamina               18632 non-null  int64
 32  strength              18632 non-null  int64
 33  long_shots            18632 non-null  int64
 34  aggression            18632 non-null  int64
 35  interceptions         18632 non-null  int64
 36  positioning           18632 non-null  int64
 37  vision                18632 non-null  int64
 38  penalties             18632 non-null  int64
 39  composure             18632 non-null  int64
 40  defensive_awareness   18632 non-null  int64
 41  standing_tackle       18632 non-null  int64
 42  sliding_tackle        18632 non-null  int64
 43  gk_diving             18632 non-null  int64
 44  gk_handling           18632 non-null  int64
 45  gk_kicking            18632 non-null  int64
 46  gk_positioning        18632 non-null  int64
 47  gk_reflexes           18632 non-null  int64
 48  normalized_name       18632 non-null  object
 49  normalized_full_name  18632 non-null  object
 50  age                   18632 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(39), object(9)
memory usage: 7.2+ MB

# One-hot encode preferrred foot

In [6]:
import pandas as pd

In [16]:
df_players = pd.read_csv('Finished_final_proj.csv')  # index=False avoids saving row indices

In [18]:
df_players['preferred_foot'].head()

0     Left
1    Right
2    Right
3    Right
4    Right
Name: preferred_foot, dtype: object

In [20]:
unique_foot = list(df_players['preferred_foot'].unique())
unique_foot

['Left', 'Right']

In [22]:
def one_hot_encode_foot(df_players, unique_foot):
    df_players_foot_encoded = pd.DataFrame()
    for foot in unique_foot:
        df_players_foot_encoded[f'preferred_foot_{foot}'] = df_players['preferred_foot'].apply(lambda x: foot_present(foot, x))

    df_players = pd.concat([df_players, df_players_foot_encoded], axis=1)
    return df_players



def foot_present(foot, unique_foot):
    if foot in unique_foot:
        return 1
    else:
        return 0

df_players = one_hot_encode_foot(df_players, unique_foot)

#print(df.head(5))

In [24]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18608 entries, 0 to 18607
Data columns (total 77 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    18608 non-null  int64
 1   player_id                     18608 non-null  int64
 2   name                          18608 non-null  object
 3   full_name                     18608 non-null  object
 4   height_cm                     18608 non-null  int64
 5   weight_kg                     18608 non-null  int64
 6   dob                           18608 non-null  object
 7   positions                     18608 non-null  object
 8   preferred_foot                18608 non-null  object
 9   body_type                     18608 non-null  object
 10  club_id                       18608 non-null  int64
 11  club_name                     18608 non-null  object
 12  club_league_id                18608 non-null  int64
 13  club_league_name              18608 non-null  object
 14  crossing                      18608 non-null  int64
 15  finishing                     18608 non-null  int64
 16  heading_accuracy              18608 non-null  int64
 17  short_passing                 18608 non-null  int64
 18  volleys                       18608 non-null  int64
 19  dribbling                     18608 non-null  int64
 20  curve                         18608 non-null  int64
 21  fk_accuracy                   18608 non-null  int64
 22  long_passing                  18608 non-null  int64
 23  ball_control                  18608 non-null  int64
 24  acceleration                  18608 non-null  int64
 25  sprint_speed                  18608 non-null  int64
 26  agility                       18608 non-null  int64
 27  reactions                     18608 non-null  int64
 28  balance                       18608 non-null  int64
 29  shot_power                    18608 non-null  int64
 30  jumping                       18608 non-null  int64
 31  stamina                       18608 non-null  int64
 32  strength                      18608 non-null  int64
 33  long_shots                    18608 non-null  int64
 34  aggression                    18608 non-null  int64
 35  interceptions                 18608 non-null  int64
 36  positioning                   18608 non-null  int64
 37  vision                        18608 non-null  int64
 38  penalties                     18608 non-null  int64
 39  composure                     18608 non-null  int64
 40  defensive_awareness           18608 non-null  int64
 41  standing_tackle               18608 non-null  int64
 42  sliding_tackle                18608 non-null  int64
 43  gk_diving                     18608 non-null  int64
 44  gk_handling                   18608 non-null  int64
 45  gk_kicking                    18608 non-null  int64
 46  gk_positioning                18608 non-null  int64
 47  gk_reflexes                   18608 non-null  int64
 48  nation_Club/Nation            2361 non-null   object
 49  nation_Career_length          2361 non-null   float64
 50  nation_Start_year_final       2361 non-null   float64
 51  nation_End/Recent_year_final  2361 non-null   float64
 52  league_Club/Nation            14760 non-null  object
 53  league_Career_length          14760 non-null  float64
 54  league_Start_year_final       14760 non-null  float64
 55  league_End/Recent_year_final  14760 non-null  float64
 56  CAM                           18608 non-null  int64
 57  CB                            18608 non-null  int64
 58  CDM                           18608 non-null  int64
 59  CF                            18608 non-null  int64
 60  CM                            18608 non-null  int64
 61  GK                            18608 non-null  int64
 62  LB                            18608 non-null  int64
 63  LM                            18608 non-null  int64
 64  LW                            18608 non-null  int64
 65  LWB                           18608 non-null  int64
 66  RB                            18608 non-null  int64
 67  RM                            18608 non-null  int64
 68  RW                            18608 non-null  int64
 69  RWB                           18608 non-null  int64
 70  ST                            18608 non-null  int64
 71  position_groups               18608 non-null  object
 72  age                           18608 non-null  int64
 73  nation_URL                    18608 non-null  object
 74  nation_Nation                 18608 non-null  object
 75  preferred_foot_Left           18608 non-null  int64
 76  preferred_foot_Right          18608 non-null  int64
dtypes: float64(6), int64(58), object(13)
memory usage: 10.9+ MB

In [26]:
df_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18608 entries, 0 to 18607
Data columns (total 77 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    18608 non-null  int64
 1   player_id                     18608 non-null  int64
 2   name                          18608 non-null  object
 3   full_name                     18608 non-null  object
 4   height_cm                     18608 non-null  int64
 5   weight_kg                     18608 non-null  int64
 6   dob                           18608 non-null  object
 7   positions                     18608 non-null  object
 8   preferred_foot                18608 non-null  object
 9   body_type                     18608 non-null  object
 10  club_id                       18608 non-null  int64
 11  club_name                     18608 non-null  object
 12  club_league_id                18608 non-null  int64
 13  club_league_name              18608 non-null  object
 14  crossing                      18608 non-null  int64
 15  finishing                     18608 non-null  int64
 16  heading_accuracy              18608 non-null  int64
 17  short_passing                 18608 non-null  int64
 18  volleys                       18608 non-null  int64
 19  dribbling                     18608 non-null  int64
 20  curve                         18608 non-null  int64
 21  fk_accuracy                   18608 non-null  int64
 22  long_passing                  18608 non-null  int64
 23  ball_control                  18608 non-null  int64
 24  acceleration                  18608 non-null  int64
 25  sprint_speed                  18608 non-null  int64
 26  agility                       18608 non-null  int64
 27  reactions                     18608 non-null  int64
 28  balance                       18608 non-null  int64
 29  shot_power                    18608 non-null  int64
 30  jumping                       18608 non-null  int64
 31  stamina                       18608 non-null  int64
 32  strength                      18608 non-null  int64
 33  long_shots                    18608 non-null  int64
 34  aggression                    18608 non-null  int64
 35  interceptions                 18608 non-null  int64
 36  positioning                   18608 non-null  int64
 37  vision                        18608 non-null  int64
 38  penalties                     18608 non-null  int64
 39  composure                     18608 non-null  int64
 40  defensive_awareness           18608 non-null  int64
 41  standing_tackle               18608 non-null  int64
 42  sliding_tackle                18608 non-null  int64
 43  gk_diving                     18608 non-null  int64
 44  gk_handling                   18608 non-null  int64
 45  gk_kicking                    18608 non-null  int64
 46  gk_positioning                18608 non-null  int64
 47  gk_reflexes                   18608 non-null  int64
 48  nation_Club/Nation            2361 non-null   object
 49  nation_Career_length          2361 non-null   float64
 50  nation_Start_year_final       2361 non-null   float64
 51  nation_End/Recent_year_final  2361 non-null   float64
 52  league_Club/Nation            14760 non-null  object
 53  league_Career_length          14760 non-null  float64
 54  league_Start_year_final       14760 non-null  float64
 55  league_End/Recent_year_final  14760 non-null  float64
 56  CAM                           18608 non-null  int64
 57  CB                            18608 non-null  int64
 58  CDM                           18608 non-null  int64
 59  CF                            18608 non-null  int64
 60  CM                            18608 non-null  int64
 61  GK                            18608 non-null  int64
 62  LB                            18608 non-null  int64
 63  LM                            18608 non-null  int64
 64  LW                            18608 non-null  int64
 65  LWB                           18608 non-null  int64
 66  RB                            18608 non-null  int64
 67  RM                            18608 non-null  int64
 68  RW                            18608 non-null  int64
 69  RWB                           18608 non-null  int64
 70  ST                            18608 non-null  int64
 71  position_groups               18608 non-null  object
 72  age                           18608 non-null  int64
 73  nation_URL                    18608 non-null  object
 74  nation_Nation                 18608 non-null  object
 75  preferred_foot_Left           18608 non-null  int64
 76  preferred_foot_Right          18608 non-null  int64
dtypes: float64(6), int64(58), object(13)
memory usage: 10.9+ MB

In [28]:
df = df_players

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18608 entries, 0 to 18607
Data columns (total 77 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    18608 non-null  int64
 1   player_id                     18608 non-null  int64
 2   name                          18608 non-null  object
 3   full_name                     18608 non-null  object
 4   height_cm                     18608 non-null  int64
 5   weight_kg                     18608 non-null  int64
 6   dob                           18608 non-null  object
 7   positions                     18608 non-null  object
 8   preferred_foot                18608 non-null  object
 9   body_type                     18608 non-null  object
 10  club_id                       18608 non-null  int64
 11  club_name                     18608 non-null  object
 12  club_league_id                18608 non-null  int64
 13  club_league_name              18608 non-null  object
 14  crossing                      18608 non-null  int64
 15  finishing                     18608 non-null  int64
 16  heading_accuracy              18608 non-null  int64
 17  short_passing                 18608 non-null  int64
 18  volleys                       18608 non-null  int64
 19  dribbling                     18608 non-null  int64
 20  curve                         18608 non-null  int64
 21  fk_accuracy                   18608 non-null  int64
 22  long_passing                  18608 non-null  int64
 23  ball_control                  18608 non-null  int64
 24  acceleration                  18608 non-null  int64
 25  sprint_speed                  18608 non-null  int64
 26  agility                       18608 non-null  int64
 27  reactions                     18608 non-null  int64
 28  balance                       18608 non-null  int64
 29  shot_power                    18608 non-null  int64
 30  jumping                       18608 non-null  int64
 31  stamina                       18608 non-null  int64
 32  strength                      18608 non-null  int64
 33  long_shots                    18608 non-null  int64
 34  aggression                    18608 non-null  int64
 35  interceptions                 18608 non-null  int64
 36  positioning                   18608 non-null  int64
 37  vision                        18608 non-null  int64
 38  penalties                     18608 non-null  int64
 39  composure                     18608 non-null  int64
 40  defensive_awareness           18608 non-null  int64
 41  standing_tackle               18608 non-null  int64
 42  sliding_tackle                18608 non-null  int64
 43  gk_diving                     18608 non-null  int64
 44  gk_handling                   18608 non-null  int64
 45  gk_kicking                    18608 non-null  int64
 46  gk_positioning                18608 non-null  int64
 47  gk_reflexes                   18608 non-null  int64
 48  nation_Club/Nation            2361 non-null   object
 49  nation_Career_length          2361 non-null   float64
 50  nation_Start_year_final       2361 non-null   float64
 51  nation_End/Recent_year_final  2361 non-null   float64
 52  league_Club/Nation            14760 non-null  object
 53  league_Career_length          14760 non-null  float64
 54  league_Start_year_final       14760 non-null  float64
 55  league_End/Recent_year_final  14760 non-null  float64
 56  CAM                           18608 non-null  int64
 57  CB                            18608 non-null  int64
 58  CDM                           18608 non-null  int64
 59  CF                            18608 non-null  int64
 60  CM                            18608 non-null  int64
 61  GK                            18608 non-null  int64
 62  LB                            18608 non-null  int64
 63  LM                            18608 non-null  int64
 64  LW                            18608 non-null  int64
 65  LWB                           18608 non-null  int64
 66  RB                            18608 non-null  int64
 67  RM                            18608 non-null  int64
 68  RW                            18608 non-null  int64
 69  RWB                           18608 non-null  int64
 70  ST                            18608 non-null  int64
 71  position_groups               18608 non-null  object
 72  age                           18608 non-null  int64
 73  nation_URL                    18608 non-null  object
 74  nation_Nation                 18608 non-null  object
 75  preferred_foot_Left           18608 non-null  int64
 76  preferred_foot_Right          18608 non-null  int64
dtypes: float64(6), int64(58), object(13)
memory usage: 10.9+ MB

# Mapping Players to unique league identifiers

# Note that Serie A and Serie A are two different leagues, the Brazilian premier league and Italian premier league.

In [39]:
unique_league_id = list(df['club_league_id'].unique())
unique_league_id

[308,
 61,
 350,
 56,
 53,
 337,
 16,
 50,
 2018,
 2017,
 338,
 41,
 353,
 39,
 20,
 19,
 2019,
 10,
 68,
 17,
 14,
 54,
 13,
 31,
 351,
 32,
 4,
 1,
 189,
 330,
 2076,
 60,
 80,
 335,
 2020,
 83,
 65,
 2012,
 336,
 332,
 2149,
 66,
 319,
 2013,
 322,
 63,
 318,
 317,
 64,
 7]

### 50 different leagues

In [42]:
unique_league = list(df['club_league_name'].unique())
unique_league

['Primeira Liga',
 'League Two',
 'Pro League',
 'Allsvenskan',
 'La Liga',
 'Primera División',
 'Ligue 1',
 'Premiership',
 'Liga Pro',
 'División de Fútbol Profesional',
 'Eliteserien',
 'Liga Profesional de Fútbol',
 'Major League Soccer',
 '2. Bundesliga',
 'Bundesliga',
 'Primera Division',
 'Eredivisie',
 'Süper Lig',
 'Ligue 2',
 'Championship',
 'La Liga 2',
 'Premier League',
 'Serie A',
 'A-League Men',
 'Serie B',
 'Superliga',
 'Super League',
 'Liga I',
 '3. Liga',
 'League One',
 'K League 1',
 'Premier Division',
 'Categoría Primera A',
 'Ekstraklasa',
 'First League',
 'Veikkausliiga',
 '1. Division',
 'Hrvatska nogometna liga',
 'Nemzeti Bajnokság I',
 'Série A']

In [44]:
league_id_name_pairs = df_players.groupby('club_league_id')['club_league_name'].unique()
print(league_id_name_pairs)

club_league_id
1                            [Superliga]
4                           [Pro League]
7                              [Série A]
10                          [Eredivisie]
13                      [Premier League]
14                        [Championship]
16                             [Ligue 1]
17                             [Ligue 2]
19                          [Bundesliga]
20                       [2. Bundesliga]
31                             [Serie A]
32                             [Serie B]
39                 [Major League Soccer]
41                         [Eliteserien]
50                         [Premiership]
53                             [La Liga]
54                           [La Liga 2]
56                         [Allsvenskan]
60                          [League One]
61                          [League Two]
63                        [Super League]
64                 [Nemzeti Bajnokság I]
65                    [Premier Division]
66                         [Ekstraklasa]
68                           [Süper Lig]
80                          [Bundesliga]
83                          [K League 1]
189                       [Super League]
308                      [Primeira Liga]
317            [Hrvatska nogometna liga]
318                        [1. Division]
319                       [First League]
322                      [Veikkausliiga]
330                             [Liga I]
332                     [Premier League]
335                   [Primera Division]
336                [Categoría Primera A]
337                   [Primera División]
338                   [Primera División]
350                         [Pro League]
351                       [A-League Men]
353         [Liga Profesional de Fútbol]
2012                      [Super League]
2013                        [Pro League]
2017    [División de Fútbol Profesional]
2018                          [Liga Pro]
2019                  [Primera Division]
2020                  [Primera Division]
2076                           [3. Liga]
2149                      [Super League]
Name: club_league_name, dtype: object

In [46]:
league_mapping = {
    1.0: 'Superliga (DEN 1) [Denmark]', #
    4.0: 'Pro League (BEL 1) [Belgium]',#
    7.0: 'Série A (BRA 1) [Brazil]',#
    10.0: 'Eredivisie (NED 1) [Netherlands]',#
    13.0: 'Premier League (ENG 1) [England]',#
    14.0: 'Championship (ENG 2) [England]',#
    16.0: 'Ligue 1 (FRA 1) [France]',#
    17.0: 'Ligue 2 (FRA 2) [France]',#
    19.0: 'Bundesliga (GER 1) [Germany]',#
    20.0: '2. Bundesliga (GER 2) [Germany]',#
    31.0: 'Serie A (ITA 1) [Italy]',#
    32.0: 'Serie B (ITA 2) [Italy]',#
    39.0: 'Major League Soccer (MLS 1) [USA]',#
    41.0: 'Eliteserien (NOR 1) [Norway]', 
    50.0: 'Premiership (SP 1) [Scotland]', 
    53.0: 'La Liga (ESP 1) [Spain]',#
    54.0: 'La Liga 2 (ESP 2) [Spain]',#
    56.0: 'Allsvenskan (SWE 1) [Sweden]',#
    60.0: 'League One (ENG 3) [England]',
    61.0: 'League Two (ENG 4) [England]',
    63.0: 'Super League (GRE 1) [Greece]',#
    64.0: 'Nemzeti Bajnokság I (HUN 1) [Hungary]',
    65.0: 'Premier Division (IRL 1) [Ireland]',
    66.0: 'Ekstraklasa (POL 1) [Poland]',#
    68.0: 'Süper Lig (TUR 1) [Turkey]',
    80.0: 'Bundesliga (AU 1) [Austria]',
    83.0: 'K League 1 (KOR 1) [South Korea]',#
    189.0: 'Super League (SWI 1) [Switzerland]',
    308.0: 'Primeira Liga (POR 1) [Portugal]',#
    317.0: 'Hrvatska nogometna liga (CRO 1) [Croatia]',#
    318.0: '1. Division (CYP 1) [Cyprus]',#
    319.0: 'First League (CZE 1) [Czech Republic]',
    322.0: 'Veikkausliiga (FIN 1) [Finland]',#
    330.0: 'Liga I (ROM 1) [Romania]',#
    332.0: 'Premier League (UKR 1) [Ukraine]',#
    335.0: 'Primera Division (CHI 1) [Chile]',#
    336.0: 'Categoría Primera A (COL 1) [Colombia]',#
    337.0: 'Primera División (PAR 1) [Paraguay]',#
    338.0: 'Primera División (URY 1) [Uruguay]',#
    350.0: 'Pro League (SAU 1) [Saudi Arabia]',#
    351.0: 'A-League Men (AUS 1) [Australia]',#
    353.0: 'Liga Profesional de Fútbol (ARG 1) [Argentina]',#
    2012.0: 'Super League (CSL 1) [China]',#
    2013.0: 'Pro League (UAE 1) [UAE]',#
    2017.0: 'División de Fútbol Profesional (BOL 1) [Bolivia]',#
    2018.0: 'Liga Pro (ECU 1) [Ecuador]',#
    2019.0: 'Primera Division (VEN 1) [Venezuela]',#
    2020.0: 'Primera Division (PER 1) [Peru]',#
    2076.0: '3. Liga (GER 3) [Germany]',#
    2149.0: 'Super League (ISL 1) [India]'#
}

In [48]:
df['league_name'] = df['club_league_id'].map(league_mapping)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18608 entries, 0 to 18607
Data columns (total 78 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    18608 non-null  int64
 1   player_id                     18608 non-null  int64
 2   name                          18608 non-null  object
 3   full_name                     18608 non-null  object
 4   height_cm                     18608 non-null  int64
 5   weight_kg                     18608 non-null  int64
 6   dob                           18608 non-null  object
 7   positions                     18608 non-null  object
 8   preferred_foot                18608 non-null  object
 9   body_type                     18608 non-null  object
 10  club_id                       18608 non-null  int64
 11  club_name                     18608 non-null  object
 12  club_league_id                18608 non-null  int64
 13  club_league_name              18608 non-null  object
 14  crossing                      18608 non-null  int64
 15  finishing                     18608 non-null  int64
 16  heading_accuracy              18608 non-null  int64
 17  short_passing                 18608 non-null  int64
 18  volleys                       18608 non-null  int64
 19  dribbling                     18608 non-null  int64
 20  curve                         18608 non-null  int64
 21  fk_accuracy                   18608 non-null  int64
 22  long_passing                  18608 non-null  int64
 23  ball_control                  18608 non-null  int64
 24  acceleration                  18608 non-null  int64
 25  sprint_speed                  18608 non-null  int64
 26  agility                       18608 non-null  int64
 27  reactions                     18608 non-null  int64
 28  balance                       18608 non-null  int64
 29  shot_power                    18608 non-null  int64
 30  jumping                       18608 non-null  int64
 31  stamina                       18608 non-null  int64
 32  strength                      18608 non-null  int64
 33  long_shots                    18608 non-null  int64
 34  aggression                    18608 non-null  int64
 35  interceptions                 18608 non-null  int64
 36  positioning                   18608 non-null  int64
 37  vision                        18608 non-null  int64
 38  penalties                     18608 non-null  int64
 39  composure                     18608 non-null  int64
 40  defensive_awareness           18608 non-null  int64
 41  standing_tackle               18608 non-null  int64
 42  sliding_tackle                18608 non-null  int64
 43  gk_diving                     18608 non-null  int64
 44  gk_handling                   18608 non-null  int64
 45  gk_kicking                    18608 non-null  int64
 46  gk_positioning                18608 non-null  int64
 47  gk_reflexes                   18608 non-null  int64
 48  nation_Club/Nation            2361 non-null   object
 49  nation_Career_length          2361 non-null   float64
 50  nation_Start_year_final       2361 non-null   float64
 51  nation_End/Recent_year_final  2361 non-null   float64
 52  league_Club/Nation            14760 non-null  object
 53  league_Career_length          14760 non-null  float64
 54  league_Start_year_final       14760 non-null  float64
 55  league_End/Recent_year_final  14760 non-null  float64
 56  CAM                           18608 non-null  int64
 57  CB                            18608 non-null  int64
 58  CDM                           18608 non-null  int64
 59  CF                            18608 non-null  int64
 60  CM                            18608 non-null  int64
 61  GK                            18608 non-null  int64
 62  LB                            18608 non-null  int64
 63  LM                            18608 non-null  int64
 64  LW                            18608 non-null  int64
 65  LWB                           18608 non-null  int64
 66  RB                            18608 non-null  int64
 67  RM                            18608 non-null  int64
 68  RW                            18608 non-null  int64
 69  RWB                           18608 non-null  int64
 70  ST                            18608 non-null  int64
 71  position_groups               18608 non-null  object
 72  age                           18608 non-null  int64
 73  nation_URL                    18608 non-null  object
 74  nation_Nation                 18608 non-null  object
 75  preferred_foot_Left           18608 non-null  int64
 76  preferred_foot_Right          18608 non-null  int64
 77  league_name                   18608 non-null  object
dtypes: float64(6), int64(58), object(14)
memory usage: 11.1+ MB

In [346]:
df.head()

,Unnamed: 0,player_id,name,full_name,height_cm,weight_kg,dob,positions,preferred_foot,body_type,...,gk_handling,gk_kicking,gk_positioning,gk_reflexes,normalized_name,normalized_full_name,age,preferred_foot_Left,preferred_foot_Right,league_name
0,0,239085,Erling Haaland,Erling Braut Haaland,195,94,2000-07-21,ST,Left,Unique,...,14,13,11,7,erling-haaland,erling-braut-haaland,24,1,0,Premier League (ENG 1) [England]
1,1,231747,Kylian Mbappé,Kylian Mbappé Lottin,182,75,1998-12-20,"ST,LW",Right,Unique,...,5,7,11,6,kylian-mbappe,kylian-mbappe-lottin,26,0,1,Ligue 1 (FRA 1) [France]
2,2,192985,Kevin De Bruyne,Kevin De Bruyne,181,75,1991-06-28,"CM,CAM",Right,Unique,...,13,5,10,13,kevin-de-bruyne,kevin-de-bruyne,33,0,1,Premier League (ENG 1) [England]
3,3,231866,Rodri,Rodrigo Hernández Cascante,191,82,1996-06-22,"CDM,CM",Right,Normal (185+),...,10,7,14,8,rodri,rodrigo-hernandez-cascante,28,0,1,Premier League (ENG 1) [England]
4,4,202126,Harry Kane,Harry Kane,188,85,1993-07-28,ST,Right,Unique,...,10,11,14,11,harry-kane,harry-kane,31,0,1,Bundesliga (GER 1) [Germany]

In [52]:
df.to_csv('Finished_final_proj_2.csv', encoding='utf-8-sig')

In [9]:
df = pd.read_csv('player_data_for_model.csv', encoding='utf-8-sig')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15013 entries, 0 to 15012
Data columns (total 67 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   player_id              15013 non-null  int64
 1   name                   15013 non-null  object
 2   full_name              15013 non-null  object
 3   height_cm              15013 non-null  int64
 4   weight_kg              15013 non-null  int64
 5   dob                    15013 non-null  object
 6   preferred_foot         15013 non-null  object
 7   body_type              15013 non-null  object
 8   club_id                15013 non-null  int64
 9   club_name              15013 non-null  object
 10  club_league_id         15013 non-null  int64
 11  club_league_name       15013 non-null  object
 12  crossing               15013 non-null  int64
 13  finishing              15013 non-null  int64
 14  heading_accuracy       15013 non-null  int64
 15  short_passing          15013 non-null  int64
 16  volleys                15013 non-null  int64
 17  dribbling              15013 non-null  int64
 18  curve                  15013 non-null  int64
 19  fk_accuracy            15013 non-null  int64
 20  long_passing           15013 non-null  int64
 21  ball_control           15013 non-null  int64
 22  acceleration           15013 non-null  int64
 23  sprint_speed           15013 non-null  int64
 24  agility                15013 non-null  int64
 25  reactions              15013 non-null  int64
 26  balance                15013 non-null  int64
 27  shot_power             15013 non-null  int64
 28  jumping                15013 non-null  int64
 29  stamina                15013 non-null  int64
 30  strength               15013 non-null  int64
 31  long_shots             15013 non-null  int64
 32  aggression             15013 non-null  int64
 33  interceptions          15013 non-null  int64
 34  positioning            15013 non-null  int64
 35  vision                 15013 non-null  int64
 36  penalties              15013 non-null  int64
 37  composure              15013 non-null  int64
 38  defensive_awareness    15013 non-null  int64
 39  standing_tackle        15013 non-null  int64
 40  sliding_tackle         15013 non-null  int64
 41  gk_diving              15013 non-null  int64
 42  gk_handling            15013 non-null  int64
 43  gk_kicking             15013 non-null  int64
 44  gk_positioning         15013 non-null  int64
 45  gk_reflexes            15013 non-null  int64
 46  Season                 15013 non-null  object
 47  Club/Nation            15013 non-null  object
 48  Career_length          15013 non-null  int64
 49  Start_year_final       15013 non-null  int64
 50  End/Recent_year_final  15013 non-null  int64
 51  CAM                    15013 non-null  int64
 52  CB                     15013 non-null  int64
 53  CDM                    15013 non-null  int64
 54  CF                     15013 non-null  int64
 55  CM                     15013 non-null  int64
 56  GK                     15013 non-null  int64
 57  LB                     15013 non-null  int64
 58  LM                     15013 non-null  int64
 59  LW                     15013 non-null  int64
 60  LWB                    15013 non-null  int64
 61  RB                     15013 non-null  int64
 62  RM                     15013 non-null  int64
 63  RW                     15013 non-null  int64
 64  RWB                    15013 non-null  int64
 65  ST                     15013 non-null  int64
 66  age                    15013 non-null  int64
dtypes: int64(58), object(9)
memory usage: 7.7+ MB

In [13]:
df_nation = pd.read_csv('nation_merged.csv', encoding='utf-8-sig')

In [41]:
import ast

In [15]:
df_nation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2671 entries, 0 to 2670
Data columns (total 61 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   player_id              2671 non-null   int64
 1   name                   2671 non-null   object
 2   full_name              2671 non-null   object
 3   height_cm              2671 non-null   int64
 4   weight_kg              2671 non-null   int64
 5   dob                    2671 non-null   object
 6   positions              2671 non-null   object
 7   preferred_foot         2671 non-null   object
 8   body_type              2671 non-null   object
 9   club_id                2671 non-null   float64
 10  club_name              2671 non-null   object
 11  club_league_id         2671 non-null   float64
 12  club_league_name       2671 non-null   object
 13  crossing               2671 non-null   int64
 14  finishing              2671 non-null   int64
 15  heading_accuracy       2671 non-null   int64
 16  short_passing          2671 non-null   int64
 17  volleys                2671 non-null   int64
 18  dribbling              2671 non-null   int64
 19  curve                  2671 non-null   int64
 20  fk_accuracy            2671 non-null   int64
 21  long_passing           2671 non-null   int64
 22  ball_control           2671 non-null   int64
 23  acceleration           2671 non-null   int64
 24  sprint_speed           2671 non-null   int64
 25  agility                2671 non-null   int64
 26  reactions              2671 non-null   int64
 27  balance                2671 non-null   int64
 28  shot_power             2671 non-null   int64
 29  jumping                2671 non-null   int64
 30  stamina                2671 non-null   int64
 31  strength               2671 non-null   int64
 32  long_shots             2671 non-null   int64
 33  aggression             2671 non-null   int64
 34  interceptions          2671 non-null   int64
 35  positioning            2671 non-null   int64
 36  vision                 2671 non-null   int64
 37  penalties              2671 non-null   int64
 38  composure              2671 non-null   int64
 39  defensive_awareness    2671 non-null   int64
 40  standing_tackle        2671 non-null   int64
 41  sliding_tackle         2671 non-null   int64
 42  gk_diving              2671 non-null   int64
 43  gk_handling            2671 non-null   int64
 44  gk_kicking             2671 non-null   int64
 45  gk_positioning         2671 non-null   int64
 46  gk_reflexes            2671 non-null   int64
 47  normalized_name        2671 non-null   object
 48  normalized_full_name   2671 non-null   object
 49  Unnamed: 0.1           2671 non-null   float64
 50  Unnamed: 0             2671 non-null   float64
 51  URL                    2671 non-null   object
 52  Name                   2671 non-null   object
 53  Type                   2671 non-null   object
 54  Season                 2671 non-null   object
 55  Club/Nation            2671 non-null   object
 56  Start_year             2671 non-null   object
 57  End/Recent_year        2671 non-null   object
 58  Career_length          2671 non-null   float64
 59  Start_year_final       2671 non-null   float64
 60  End/Recent_year_final  2671 non-null   float64
dtypes: float64(7), int64(37), object(17)
memory usage: 1.2+ MB

In [43]:
df_nation['Club/Nation'].head(5)

0    ['Norway', 'Norway', 'Norway', 'Norway', 'Norw...
1    ['France', 'France', 'France', 'France', 'Fran...
2    ['Belgium', 'Belgium', 'Belgium', 'Belgium', '...
3    ['Spain', 'Spain', 'Spain', 'Spain', 'Spain', ...
4    ['England', 'England', 'England', 'England', '...
Name: Club/Nation, dtype: object

In [57]:
def extract_nation(full_name_string):

    full_name_string = ast.literal_eval(full_name_string)

    unique_countries = set(full_name_string)

    return unique_countries


df_nation['Extracted_Nation'] = df_nation['Club/Nation'].apply(extract_nation)

df_nation[['Club/Nation', 'Extracted_Nation']].head(50)

,Club/Nation,Extracted_Nation
0,"['Norway', 'Norway', 'Norway', 'Norway', 'Norw...",{Norway}
1,"['France', 'France', 'France', 'France', 'Fran...",{France}
2,"['Belgium', 'Belgium', 'Belgium', 'Belgium', '...",{Belgium}
3,"['Spain', 'Spain', 'Spain', 'Spain', 'Spain', ...",{Spain}
4,"['England', 'England', 'England', 'England', '...",{England}
5,"['Belgium', 'Belgium', 'Belgium', 'Belgium', '...",{Belgium}
6,"['Poland', 'Poland', 'Poland', 'Poland', 'Pola...",{Poland}
7,"['Argentina', 'Argentina', 'Argentina', 'Argen...",{Argentina}
8,"['Brazil', 'Brazil', 'Brazil']",{Brazil}
9,"['Egypt', 'Egypt', 'Egypt', 'Egypt', 'Egypt', ...",{Egypt}
10,"['Netherlands', 'Netherlands', 'Netherlands', ...",{Netherlands}
11,"['Germany', 'Germany', 'Germany', 'Germany', '...",{Germany}
12,"['England', 'England', 'England', 'England', '...",{England}
13,"['Uruguay', 'Uruguay']",{Uruguay}
14,"['Argentina', 'Argentina', 'Argentina', 'Argen...",{Argentina}
15,"['Brazil', 'Brazil']",{Brazil}
16,"['Slovenia', 'Slovenia', 'Slovenia', 'Slovenia...",{Slovenia}
17,"['France', 'France', 'France', 'France', 'Fran...",{France}
18,"['France', 'France', 'France', 'France', 'Fran...",{France}
19,"['Germany', 'Germany', 'Germany', 'Germany', '...",{Germany}
20,"['England', 'England', 'England', 'England', '...",{England}
21,['Switzerland'],{Switzerland}
22,"['England', 'England', 'England', 'England', '...","{England, Republic of Ireland}"
23,"['Italy', 'Italy', 'Italy', 'Italy', 'Italy', ...",{Italy}
24,"['Netherlands', 'Netherlands', 'Netherlands', ...",{Netherlands}
25,"['France', 'France', 'France', 'France', 'Fran...",{France}
26,"['Germany', 'Germany', 'Germany', 'Germany', '...",{Germany}
27,"['Portugal', 'Portugal', 'Portugal', 'Portugal...",{Portugal}
28,"['Brazil', 'Brazil', 'Brazil', 'Brazil', 'Braz...",{Brazil}
29,"['Korea Republic', 'Korea Republic', 'Korea Re...",{Korea Republic}
30,"['Germany', 'Germany', 'Germany', 'Germany', '...",{Germany}
31,"['Germany', 'Germany', 'Germany', 'Germany', '...",{Germany}
32,"['Spain', 'Spain', 'Spain', 'Spain', 'Spain']",{Spain}
33,"['England', 'England', 'England', 'England']",{England}
34,"['France', 'France', 'France', 'France', 'Fran...",{France}
35,"['England', 'England', 'England', 'England', '...",{England}
36,"['Italy', 'Italy', 'Italy', 'Italy', 'Italy', ...",{Italy}
37,"['Germany', 'Germany', 'Germany', 'Germany', '...",{Germany}
38,"['Scotland', 'Scotland', 'Scotland', 'Scotland...",{Scotland}
39,"['Argentina', 'Argentina', 'Argentina', 'Argen...",{Argentina}
40,"['Portugal', 'Portugal', 'Portugal', 'Portugal...",{Portugal}
41,"['Spain', 'Spain']",{Spain}
42,"['Türkiye', 'Türkiye', 'Türkiye', 'Türkiye', '...",{Türkiye}
43,"['Germany', 'Germany', 'Germany', 'Germany', '...",{Germany}
44,"['Argentina', 'Argentina', 'Argentina', 'Argen...",{Argentina}
45,"['Germany', 'Germany', 'Germany', 'Germany', '...",{Germany}
46,"['Poland', 'Poland', 'Poland', 'Poland', 'Pola...",{Poland}
47,"['Switzerland', 'Switzerland', 'Switzerland', ...",{Switzerland}
48,"['Croatia', 'Croatia', 'Croatia', 'Croatia', '...",{Croatia}
49,"['France', 'France', 'France', 'France']",{France}

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15013 entries, 0 to 15012
Data columns (total 68 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   player_id              15013 non-null  int64
 1   name                   15013 non-null  object
 2   full_name              15013 non-null  object
 3   height_cm              15013 non-null  int64
 4   weight_kg              15013 non-null  int64
 5   dob                    15013 non-null  object
 6   preferred_foot         15013 non-null  object
 7   body_type              15013 non-null  object
 8   club_id                15013 non-null  int64
 9   club_name              15013 non-null  object
 10  club_league_id         15013 non-null  int64
 11  club_league_name       15013 non-null  object
 12  crossing               15013 non-null  int64
 13  finishing              15013 non-null  int64
 14  heading_accuracy       15013 non-null  int64
 15  short_passing          15013 non-null  int64
 16  volleys                15013 non-null  int64
 17  dribbling              15013 non-null  int64
 18  curve                  15013 non-null  int64
 19  fk_accuracy            15013 non-null  int64
 20  long_passing           15013 non-null  int64
 21  ball_control           15013 non-null  int64
 22  acceleration           15013 non-null  int64
 23  sprint_speed           15013 non-null  int64
 24  agility                15013 non-null  int64
 25  reactions              15013 non-null  int64
 26  balance                15013 non-null  int64
 27  shot_power             15013 non-null  int64
 28  jumping                15013 non-null  int64
 29  stamina                15013 non-null  int64
 30  strength               15013 non-null  int64
 31  long_shots             15013 non-null  int64
 32  aggression             15013 non-null  int64
 33  interceptions          15013 non-null  int64
 34  positioning            15013 non-null  int64
 35  vision                 15013 non-null  int64
 36  penalties              15013 non-null  int64
 37  composure              15013 non-null  int64
 38  defensive_awareness    15013 non-null  int64
 39  standing_tackle        15013 non-null  int64
 40  sliding_tackle         15013 non-null  int64
 41  gk_diving              15013 non-null  int64
 42  gk_handling            15013 non-null  int64
 43  gk_kicking             15013 non-null  int64
 44  gk_positioning         15013 non-null  int64
 45  gk_reflexes            15013 non-null  int64
 46  Season                 15013 non-null  object
 47  Club/Nation            15013 non-null  object
 48  Career_length          15013 non-null  int64
 49  Start_year_final       15013 non-null  int64
 50  End/Recent_year_final  15013 non-null  int64
 51  CAM                    15013 non-null  int64
 52  CB                     15013 non-null  int64
 53  CDM                    15013 non-null  int64
 54  CF                     15013 non-null  int64
 55  CM                     15013 non-null  int64
 56  GK                     15013 non-null  int64
 57  LB                     15013 non-null  int64
 58  LM                     15013 non-null  int64
 59  LW                     15013 non-null  int64
 60  LWB                    15013 non-null  int64
 61  RB                     15013 non-null  int64
 62  RM                     15013 non-null  int64
 63  RW                     15013 non-null  int64
 64  RWB                    15013 non-null  int64
 65  ST                     15013 non-null  int64
 66  age                    15013 non-null  int64
 67  Extracted_Nation       15013 non-null  object
dtypes: int64(58), object(10)
memory usage: 7.8+ MB

In [63]:
df['player_id'].head()

0    19541
1    20801
2    23823
3    25798
4    49472
Name: player_id, dtype: int64

In [65]:
df_nation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2671 entries, 0 to 2670
Data columns (total 62 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   player_id              2671 non-null   int64
 1   name                   2671 non-null   object
 2   full_name              2671 non-null   object
 3   height_cm              2671 non-null   int64
 4   weight_kg              2671 non-null   int64
 5   dob                    2671 non-null   object
 6   positions              2671 non-null   object
 7   preferred_foot         2671 non-null   object
 8   body_type              2671 non-null   object
 9   club_id                2671 non-null   float64
 10  club_name              2671 non-null   object
 11  club_league_id         2671 non-null   float64
 12  club_league_name       2671 non-null   object
 13  crossing               2671 non-null   int64
 14  finishing              2671 non-null   int64
 15  heading_accuracy       2671 non-null   int64
 16  short_passing          2671 non-null   int64
 17  volleys                2671 non-null   int64
 18  dribbling              2671 non-null   int64
 19  curve                  2671 non-null   int64
 20  fk_accuracy            2671 non-null   int64
 21  long_passing           2671 non-null   int64
 22  ball_control           2671 non-null   int64
 23  acceleration           2671 non-null   int64
 24  sprint_speed           2671 non-null   int64
 25  agility                2671 non-null   int64
 26  reactions              2671 non-null   int64
 27  balance                2671 non-null   int64
 28  shot_power             2671 non-null   int64
 29  jumping                2671 non-null   int64
 30  stamina                2671 non-null   int64
 31  strength               2671 non-null   int64
 32  long_shots             2671 non-null   int64
 33  aggression             2671 non-null   int64
 34  interceptions          2671 non-null   int64
 35  positioning            2671 non-null   int64
 36  vision                 2671 non-null   int64
 37  penalties              2671 non-null   int64
 38  composure              2671 non-null   int64
 39  defensive_awareness    2671 non-null   int64
 40  standing_tackle        2671 non-null   int64
 41  sliding_tackle         2671 non-null   int64
 42  gk_diving              2671 non-null   int64
 43  gk_handling            2671 non-null   int64
 44  gk_kicking             2671 non-null   int64
 45  gk_positioning         2671 non-null   int64
 46  gk_reflexes            2671 non-null   int64
 47  normalized_name        2671 non-null   object
 48  normalized_full_name   2671 non-null   object
 49  Unnamed: 0.1           2671 non-null   float64
 50  Unnamed: 0             2671 non-null   float64
 51  URL                    2671 non-null   object
 52  Name                   2671 non-null   object
 53  Type                   2671 non-null   object
 54  Season                 2671 non-null   object
 55  Club/Nation            2671 non-null   object
 56  Start_year             2671 non-null   object
 57  End/Recent_year        2671 non-null   object
 58  Career_length          2671 non-null   float64
 59  Start_year_final       2671 non-null   float64
 60  End/Recent_year_final  2671 non-null   float64
 61  Extracted_Nation       2671 non-null   object
dtypes: float64(7), int64(37), object(18)
memory usage: 1.3+ MB

In [129]:
df = pd.read_csv('players_with_groups.csv')

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15013 entries, 0 to 15012
Data columns (total 68 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   player_id              15013 non-null  int64
 1   name                   15013 non-null  object
 2   full_name              15013 non-null  object
 3   height_cm              15013 non-null  int64
 4   weight_kg              15013 non-null  int64
 5   dob                    15013 non-null  object
 6   preferred_foot         15013 non-null  object
 7   body_type              15013 non-null  object
 8   club_id                15013 non-null  int64
 9   club_name              15013 non-null  object
 10  club_league_id         15013 non-null  int64
 11  club_league_name       15013 non-null  object
 12  crossing               15013 non-null  int64
 13  finishing              15013 non-null  int64
 14  heading_accuracy       15013 non-null  int64
 15  short_passing          15013 non-null  int64
 16  volleys                15013 non-null  int64
 17  dribbling              15013 non-null  int64
 18  curve                  15013 non-null  int64
 19  fk_accuracy            15013 non-null  int64
 20  long_passing           15013 non-null  int64
 21  ball_control           15013 non-null  int64
 22  acceleration           15013 non-null  int64
 23  sprint_speed           15013 non-null  int64
 24  agility                15013 non-null  int64
 25  reactions              15013 non-null  int64
 26  balance                15013 non-null  int64
 27  shot_power             15013 non-null  int64
 28  jumping                15013 non-null  int64
 29  stamina                15013 non-null  int64
 30  strength               15013 non-null  int64
 31  long_shots             15013 non-null  int64
 32  aggression             15013 non-null  int64
 33  interceptions          15013 non-null  int64
 34  positioning            15013 non-null  int64
 35  vision                 15013 non-null  int64
 36  penalties              15013 non-null  int64
 37  composure              15013 non-null  int64
 38  defensive_awareness    15013 non-null  int64
 39  standing_tackle        15013 non-null  int64
 40  sliding_tackle         15013 non-null  int64
 41  gk_diving              15013 non-null  int64
 42  gk_handling            15013 non-null  int64
 43  gk_kicking             15013 non-null  int64
 44  gk_positioning         15013 non-null  int64
 45  gk_reflexes            15013 non-null  int64
 46  Season                 15013 non-null  object
 47  Club/Nation            15013 non-null  object
 48  Career_length          15013 non-null  int64
 49  Start_year_final       15013 non-null  int64
 50  End/Recent_year_final  15013 non-null  int64
 51  CAM                    15013 non-null  int64
 52  CB                     15013 non-null  int64
 53  CDM                    15013 non-null  int64
 54  CF                     15013 non-null  int64
 55  CM                     15013 non-null  int64
 56  GK                     15013 non-null  int64
 57  LB                     15013 non-null  int64
 58  LM                     15013 non-null  int64
 59  LW                     15013 non-null  int64
 60  LWB                    15013 non-null  int64
 61  RB                     15013 non-null  int64
 62  RM                     15013 non-null  int64
 63  RW                     15013 non-null  int64
 64  RWB                    15013 non-null  int64
 65  ST                     15013 non-null  int64
 66  age                    15013 non-null  int64
 67  position_groups        15013 non-null  object
dtypes: int64(58), object(10)
memory usage: 7.8+ MB

In [133]:
df.head()

,player_id,name,full_name,height_cm,weight_kg,dob,preferred_foot,body_type,club_id,club_name,...,LM,LW,LWB,RB,RM,RW,RWB,ST,age,position_groups
0,19541,Glenn Morris,Glenn James Morris,183,70,1983-12-20,Right,Normal (170-185),1802,Gillingham,...,0,0,0,0,0,0,0,0,41,['goalkeeper']
1,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,187,85,1985-02-05,Right,Unique,112139,Al Nassr,...,0,0,0,0,0,0,0,1,40,['attacker']
2,23823,Andreas Johansson,Karl Tommy Andreas Johansson,184,78,1982-03-10,Right,Lean (170-185),321,Halmstad,...,0,0,0,0,0,0,0,0,43,['defender']
3,25798,Roque Santa Cruz,Roque Luis Santa Cruz Cantero,191,93,1981-08-16,Right,Normal (185+),111008,Libertad,...,0,0,0,0,0,0,0,1,43,['attacker']
4,49472,Ludovic Butelle,Ludovic Butelle,188,84,1983-04-03,Left,Normal (185+),379,Stade de Reims,...,0,0,0,0,0,0,0,0,42,['goalkeeper']

In [135]:
df_nation = pd.read_csv('player_nation_with_urls.csv')

In [147]:
nation_only = pd.read_csv('sofifa-final-withNation.csv')

In [149]:
nation_only.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18821 entries, 0 to 18820
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   18821 non-null  int64
 1   URL          18821 non-null  object
 2   Player Name  18821 non-null  object
 3   Nation       18821 non-null  object
 4   Name         18821 non-null  object
dtypes: int64(1), object(4)
memory usage: 735.3+ KB

In [137]:
df_nation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15013 entries, 0 to 15012
Data columns (total 78 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             15013 non-null  int64
 1   Unnamed: 0_x           15013 non-null  int64
 2   player_id              15013 non-null  int64
 3   name                   15013 non-null  object
 4   full_name              15013 non-null  object
 5   height_cm              15013 non-null  int64
 6   weight_kg              15013 non-null  int64
 7   dob                    15013 non-null  object
 8   positions              15013 non-null  object
 9   preferred_foot         15013 non-null  object
 10  body_type              15013 non-null  object
 11  club_id                15013 non-null  int64
 12  club_name              15013 non-null  object
 13  club_league_id         15013 non-null  int64
 14  club_league_name       15013 non-null  object
 15  crossing               15013 non-null  int64
 16  finishing              15013 non-null  int64
 17  heading_accuracy       15013 non-null  int64
 18  short_passing          15013 non-null  int64
 19  volleys                15013 non-null  int64
 20  dribbling              15013 non-null  int64
 21  curve                  15013 non-null  int64
 22  fk_accuracy            15013 non-null  int64
 23  long_passing           15013 non-null  int64
 24  ball_control           15013 non-null  int64
 25  acceleration           15013 non-null  int64
 26  sprint_speed           15013 non-null  int64
 27  agility                15013 non-null  int64
 28  reactions              15013 non-null  int64
 29  balance                15013 non-null  int64
 30  shot_power             15013 non-null  int64
 31  jumping                15013 non-null  int64
 32  stamina                15013 non-null  int64
 33  strength               15013 non-null  int64
 34  long_shots             15013 non-null  int64
 35  aggression             15013 non-null  int64
 36  interceptions          15013 non-null  int64
 37  positioning            15013 non-null  int64
 38  vision                 15013 non-null  int64
 39  penalties              15013 non-null  int64
 40  composure              15013 non-null  int64
 41  defensive_awareness    15013 non-null  int64
 42  standing_tackle        15013 non-null  int64
 43  sliding_tackle         15013 non-null  int64
 44  gk_diving              15013 non-null  int64
 45  gk_handling            15013 non-null  int64
 46  gk_kicking             15013 non-null  int64
 47  gk_positioning         15013 non-null  int64
 48  gk_reflexes            15013 non-null  int64
 49  normalized_name        15013 non-null  object
 50  normalized_full_name   15013 non-null  object
 51  Unnamed: 0.1           15013 non-null  float64
 52  Unnamed: 0_y           15013 non-null  float64
 53  URL                    15013 non-null  object
 54  Name                   15013 non-null  object
 55  Type                   15013 non-null  object
 56  Season                 15013 non-null  object
 57  Club/Nation            15013 non-null  object
 58  Start_year             15013 non-null  object
 59  End/Recent_year        15013 non-null  object
 60  Career_length          15013 non-null  float64
 61  Start_year_final       15013 non-null  float64
 62  End/Recent_year_final  15013 non-null  float64
 63  CAM                    15013 non-null  int64
 64  CB                     15013 non-null  int64
 65  CDM                    15013 non-null  int64
 66  CF                     15013 non-null  int64
 67  CM                     15013 non-null  int64
 68  GK                     15013 non-null  int64
 69  LB                     15013 non-null  int64
 70  LM                     15013 non-null  int64
 71  LW                     15013 non-null  int64
 72  LWB                    15013 non-null  int64
 73  RB                     15013 non-null  int64
 74  RM                     15013 non-null  int64
 75  RW                     15013 non-null  int64
 76  RWB                    15013 non-null  int64
 77  ST                     15013 non-null  int64
dtypes: float64(5), int64(56), object(17)
memory usage: 8.9+ MB

In [145]:
df_nation['URL'].head()

0    https://sofifa.com/player/19541/glenn-morris/2...
1    https://sofifa.com/player/243812/rodrygo-silva...
2    https://sofifa.com/player/23823/andreas-johans...
3    https://sofifa.com/player/25798/roque-santa-cr...
4    https://sofifa.com/player/49472/ludovic-butell...
Name: URL, dtype: object

In [103]:
df.head()

,player_id,name,full_name,height_cm,weight_kg,dob,preferred_foot,body_type,club_id,club_name,...,LWB,RB,RM,RW,RWB,ST,age,league_name,normalized_name,normalized_full_name
0,19541,Glenn Morris,Glenn James Morris,183,70,1983-12-20,Right,Normal (170-185),1802,Gillingham,...,0,0,0,0,0,0,41,League Two (ENG 4) [England],glenn-morris,glenn-james-morris
1,20801,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,187,85,1985-02-05,Right,Unique,112139,Al Nassr,...,0,0,0,0,0,1,40,Pro League (SAU 1) [Saudi Arabia],cristiano-ronaldo,cristiano-ronaldo-dos-santos-aveiro
2,23823,Andreas Johansson,Karl Tommy Andreas Johansson,184,78,1982-03-10,Right,Lean (170-185),321,Halmstad,...,0,0,0,0,0,0,43,Allsvenskan (SWE 1) [Sweden],andreas-johansson,karl-tommy-andreas-johansson
3,25798,Roque Santa Cruz,Roque Luis Santa Cruz Cantero,191,93,1981-08-16,Right,Normal (185+),111008,Libertad,...,0,0,0,0,0,1,43,Primera División (PAR 1) [Paraguay],roque-santa-cruz,roque-luis-santa-cruz-cantero
4,49472,Ludovic Butelle,Ludovic Butelle,188,84,1983-04-03,Left,Normal (185+),379,Stade de Reims,...,0,0,0,0,0,0,42,Ligue 1 (FRA 1) [France],ludovic-butelle,ludovic-butelle

In [117]:
league_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13771 entries, 0 to 15169
Data columns (total 75 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   player_id              13771 non-null  int64
 1   name                   13771 non-null  object
 2   full_name              13771 non-null  object
 3   height_cm              13771 non-null  int64
 4   weight_kg              13771 non-null  int64
 5   dob                    13771 non-null  object
 6   preferred_foot         13771 non-null  object
 7   body_type              13771 non-null  object
 8   club_id                13771 non-null  int64
 9   club_name              13771 non-null  object
 10  club_league_id         13771 non-null  int64
 11  club_league_name       13771 non-null  object
 12  crossing               13771 non-null  int64
 13  finishing              13771 non-null  int64
 14  heading_accuracy       13771 non-null  int64
 15  short_passing          13771 non-null  int64
 16  volleys                13771 non-null  int64
 17  dribbling              13771 non-null  int64
 18  curve                  13771 non-null  int64
 19  fk_accuracy            13771 non-null  int64
 20  long_passing           13771 non-null  int64
 21  ball_control           13771 non-null  int64
 22  acceleration           13771 non-null  int64
 23  sprint_speed           13771 non-null  int64
 24  agility                13771 non-null  int64
 25  reactions              13771 non-null  int64
 26  balance                13771 non-null  int64
 27  shot_power             13771 non-null  int64
 28  jumping                13771 non-null  int64
 29  stamina                13771 non-null  int64
 30  strength               13771 non-null  int64
 31  long_shots             13771 non-null  int64
 32  aggression             13771 non-null  int64
 33  interceptions          13771 non-null  int64
 34  positioning            13771 non-null  int64
 35  vision                 13771 non-null  int64
 36  penalties              13771 non-null  int64
 37  composure              13771 non-null  int64
 38  defensive_awareness    13771 non-null  int64
 39  standing_tackle        13771 non-null  int64
 40  sliding_tackle         13771 non-null  int64
 41  gk_diving              13771 non-null  int64
 42  gk_handling            13771 non-null  int64
 43  gk_kicking             13771 non-null  int64
 44  gk_positioning         13771 non-null  int64
 45  gk_reflexes            13771 non-null  int64
 46  Season                 13771 non-null  object
 47  Club/Nation            13771 non-null  object
 48  Career_length          13771 non-null  int64
 49  Start_year_final       13771 non-null  int64
 50  End/Recent_year_final  13771 non-null  int64
 51  CAM                    13771 non-null  int64
 52  CB                     13771 non-null  int64
 53  CDM                    13771 non-null  int64
 54  CF                     13771 non-null  int64
 55  CM                     13771 non-null  int64
 56  GK                     13771 non-null  int64
 57  LB                     13771 non-null  int64
 58  LM                     13771 non-null  int64
 59  LW                     13771 non-null  int64
 60  LWB                    13771 non-null  int64
 61  RB                     13771 non-null  int64
 62  RM                     13771 non-null  int64
 63  RW                     13771 non-null  int64
 64  RWB                    13771 non-null  int64
 65  ST                     13771 non-null  int64
 66  age                    13771 non-null  int64
 67  league_name            13771 non-null  object
 68  normalized_name        13771 non-null  object
 69  normalized_full_name   13771 non-null  object
 70  Unnamed: 0             13771 non-null  float64
 71  URL                    13771 non-null  object
 72  Player Name            13771 non-null  object
 73  Nation                 13771 non-null  object
 74  Name                   13771 non-null  object
dtypes: float64(1), int64(58), object(16)
memory usage: 8.0+ MB